### DISCUSSION TITLE
redisson under yhe hood stuff

### DISCUSSION THREAD

**Discussion by DmitryShabalin** [redisson/redisson#4873] [Q&A]
Redisson creates redisson__idle__set, redisson__timeout__set etc. Is some where information about that? By redisinsign profiling them generate 99% activity,

**Comment by mrniko** [comment]
These sets are used to track expired map entires.

**Reply by DmitryShabalin** [reply]
@mrniko so this is normal? (from https://stackoverflow.com/questions/75483200/redisson-is-spamming-redis)
i checked app in local and opening some pages (no any hard work under the hood, just getting by id and external id) and there are profiling from redisinsignt 
![image](https://user-images.githubusercontent.com/2506448/220088417-b49fecbe-af78-433e-872a-7f27cb21831f.png)

**Comment by mrniko** [comment]
Try to increase https://github.com/redisson/redisson/wiki/2.-Configuration#mincleanupdelay setting

**Reply by DmitryShabalin** [reply]
set up to 60 but no luck - the same numbers at profiling, here is my singleServerConfig 

```
# https://github.com/redisson/redisson/wiki/2.-Configuration#26-single-instance-mode
singleServerConfig:
  address: "redis://${redis.connection.host}:${redis.connection.port}"
#  connectionMinimumIdleSize: "5"
  # Redis server response timeout. Starts to countdown when Redis command was successfully sent. Value in milliseconds.
  timeout: "10000"
  connectionPoolSize: 64
  # Timeout during connecting to any Redis server.
#  connectTimeout: "10000"
#  pingConnectionInterval: "1000"
#codec: !<org.redisson.codec.MarshallingCodec> {}
minCleanUpDelay: 60
```
