### DISCUSSION TITLE
Is declarative config enough to ensure single-server mode is activated?

### DISCUSSION THREAD

**Discussion by lkk7** [redisson/redisson#6456] [Q&A] [answered]
This may be a bit nit-picky, but:

The docs specify everywhere that you activate the single server config mode by:
```java
config.useSingleServer()
```

But if I don't use a programmatic config, just the declarative one, is this enough to ensure that the single-server mode is activated?

E.g. when working with Micronaut:

```yaml
redisson:
  single-server-config:
     address: "redis://127.0.0.1:6379"
  threads: 16
  netty-threads: 32
```

And later in the code:
```java
@Inject
RedissonClient redisson // Is it guaranteed that this is a single-server configured client?
```
