### ISSUE TITLE
Redisson trying to connect to a dead slave on sentinel setup

### ISSUE THREAD

**Issue by leolimajr** [redisson/redisson#1108]
Guys,

I have a redis 3.2 setup with sentinel (3 nodes). I'm using redisson 2x. 
I'm performing some HA tests, dropping some slaves or making them fail to test the resilience of the system.

My simple config:

```YAML
# redisson configuration for redis servers
# see : https://github.com/mrniko/redisson/wiki/2.-Configuration

sentinelServersConfig:
  idleConnectionTimeout: 10000
  pingTimeout: 1000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  reconnectionTimeout: 3000
  failedAttempts: 3
  subscriptionsPerConnection: 5
  clientName: "bar"
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveConnectionMinimumIdleSize: 10
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 10
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  sentinelAddresses: ["redis://sentinel.dev.foo.net:30039"]
  masterName: "mymaster"
codec: !<org.redisson.codec.SnappyCodec> {}
```

So I got this scenario where one of slaves is disconnected and with error on master link (check lines 10 and 33):
```
sentinel slaves mymaster
 1) "name"
  2)   "192.168.112.20:30079"
  3)   "ip"
  4)   "192.168.112.20"
  5)   "port"
  6)   "30079"
  7)   "runid"
  8)   "5533a09464369994a52b4d4a80e490a8613920ce"
  9)   "flags"
  10)   "s_down,slave,disconnected"**
  11)   "link-pending-commands"
  12)   "57515"
  13)   "link-refcount"
  14)   "1"
  15)   "last-ping-sent"
  16)   "60798317"
  17)   "last-ok-ping-reply"
  18)   "60799373"
  19)   "last-ping-reply"
  20)   "60799373"
  21)   "s-down-time"
  22)   "60788261"
  23)   "down-after-milliseconds"
  24)   "10000"
  25)   "info-refresh"
  26)   "60805267"
  27)   "role-reported"
  28)   "slave"
  29)   "role-reported-time"
  30)   "146523425"
  31)   "master-link-down-time"
  32)   "1508340989000"
  33)   "master-link-status"
  34)   "err"
  35)   "master-host"
  36)   "192.168.112.21"
  37)   "master-port"
  38)   "30079"
  39)   "slave-priority"
  40)   "100"
  41)   "slave-repl-offset"
  42)   "1"
```
The problem is that redisson tries to connect to this slave for reading regardless of its status instead of picking another slave.  Shouldn't redisson consider sentinel flags in this case? Maybe it is just a configuration I'm missing.
