### ISSUE TITLE
Sentinel failover with pub/sub failure

### ISSUE THREAD

**Issue by leolimajr** [redisson/redisson#1280]
Guys,

I'm facing na issue I'd like to share and get insights from you.  
We run a sentinel cluster which is composed by (3 sentinels, 1 master and 2 slaves). The application can have dozens of instances and is connected to to this cluster via redisson 2.10.7 and redis 3.2.10

Eventually in an event of failover pub/sub messages seems to not be delivered to redisson clients (I say that because SentinelConnectionManager logs for failover are not present in system logs).

The only log after that is:
```
RedisConnection# [redisClient=[addr=redis://#:#], channel=[id: #x#, L:#/#:# ! R:/#:#]] is not active!
```

After that, redisson becomes irresponsive and seems to never recover and the only way to fix it is to restart the application node. 

Redis cluster is confirmed to be working properly (as restart of application nodes alone fixes the issue)

According to [redis client guideline](https://redis.io/topics/sentinel-clients) pub/sub messages are not guaranteed to be delivery and should not replace the pooling mechanism to check the cluster status.  I need to dig a little bit into the redisson code but it seems to strongly rely on pub/sub only.

I'm trying to reproduce it locally and build a test case, but it is being tricky.

Have you ever experienced this problem before?

redisson config as follows:

```
sentinelServersConfig:
 idleConnectionTimeout: 10000
 pingTimeout: 1000
 connectTimeout: 5000
 timeout: 3000
 retryAttempts: 3
 retryInterval: 1500
 reconnectionTimeout: 3000
 failedAttempts: 3
 clientName: "shop"
 loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
 slaveConnectionMinimumIdleSize: 0
 slaveConnectionPoolSize: 0
 masterConnectionMinimumIdleSize: 16
 masterConnectionPoolSize: 256
 readMode: "MASTER"
 subscriptionMode: "MASTER"
 sentinelAddresses: ["redis://sentinel1.dev.foo.net:30050",
     "redis://sentinel2.foo.net:30050",
     "redis://sentinel3.foo.net:30050"]
 masterName: "sandbox"
codec: !<org.redisson.codec.FstCodec> {}
```
