### ISSUE TITLE
通过Tomcat-Session-Manager管理session，访问速度特别慢

### ISSUE THREAD

**Issue by MemoryL7** [redisson/redisson#1530]
实际通过nginx在一台机器上模拟多服务测试﻿

### Expected behavior
多应用服务可以实现session共享，redis记录session数据，正常访问系统

### Actual behavior
可以实现session共享redis记录数据，但是访问系统速度变慢

### Steps to reproduce or test case
实际操作按照下面操作配置
https://github.com/redisson/redisson/wiki/14.-%E7%AC%AC%E4%B8%89%E6%96%B9%E6%A1%86%E6%9E%B6%E6%95%B4%E5%90%88#145-tomcat%E4%BC%9A%E8%AF%9D%E7%AE%A1%E7%90%86%E5%99%A8tomcat-session-manager

### Redis version
4.0.9

### Redisson version
3.4.3

### Tomcat version
8.5.28

### Redisson configuration
Tomcat config配置文件
```
singleServerConfig:
  address: redis://127.0.0.1:6379
  password: asd123qwe
```

redisson config
```
redisson:
    address: redis://127.0.0.1:6379
    password: asd123qwe
    thread: 4
    codec: org.redisson.client.codec.StringCodec
    connectionMinimumIdleSize: 12
    idleConnectionTimeout: 10000
    pingTimeout: 1000
    connectTimeout: 10000
    timeout: 3000
    retryAttempts: 2
    retryInterval: 1500
    reconnectionTimeout: 3000
    failedAttempts: 2
    subscriptionsPerConnection: 5
    clientName: firstClient
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 5
    connectionPoolSize: 64
    database: 0
    dnsMonitoring: false
    dnsMonitoringInterval: 5000
```
