### ISSUE TITLE
Default values for local cache in RedissonSpringLocalCachedCacheManager

### ISSUE THREAD

**Issue by bkoroliuk-amplify** [redisson/redisson#1687]
What are default values for the mentioned below properties?
Are these values from LocalCachedMapOptions::defaults()?
I see that local caches work, but only ttl, idle and maxSize are defined.
```
 localCacheOptions:
    evictionPolicy: "LRU"
    reconnectionStrategy: "CLEAR"
    syncStrategy: "UPDATE"
    writeMode: "WRITE_THROUGH"
    cacheSize: 1000
    timeToLiveInMillis: 300000
    maxIdleInMillis: 300000
```
