### ISSUE TITLE
Problem with radius() method and AWS ElastiCache cluster and readMode=SLAVE

### ISSUE THREAD

**Issue by duribe76** [redisson/redisson#1768]
### Expected behavior
A call to retrieve the items from a RGeo key based on radius should work in an AWS ElastiCache replicated setup using readMode SLAVE

### Actual behavior
Since all these calls are considered read-only by Redisson as opposed to write by Redis/ElastiCache, they are all sent to read-only slaves. We get the exception below instead. Please note I've masked actual IP addresses and host names with x's, and replaced the key names and coordinates.
READONLY You can't write against a read only slave.. channel: [id: 0xad662a07, L:/xx.x.x.230:46140 - R:xxx-01.xxx.0001.use1.cache.amazonaws.com/xx.x.xx.xxx:6379] command: (GEORADIUS), params: [{geo}geoKey:coords, -100.000000, 30.000000, 50.0, mi, ASC]

### Steps to reproduce or test case
Configure Redisson to use a replicated ElastiCache cluster with readMode=SLAVE and use radius() method for a RGeo object

### Redis version
AWS ElastiCache

### Redisson version
3.8.1

### Redisson configuration
In Code
```
String[] redisNodes = { "xxx-01.xxx.0001.use1.cache.amazonaws.com:6379", "xxx-02.xxx.0001.use1.cache.amazonaws.com:6379", "xxx-03.xxx.0001.use1.cache.amazonaws.com:6379" }
config.useReplicatedServers().addNodeAddress(redisNodes);
``` 

In YAML
```
replicatedServersConfig:
    idleConnectionTimeout: 10000
    pingTimeout: 1000
    connectTimeout: 10000
    timeout: 3000
    retryAttempts: 3
    retryInterval: 1500
    failedSlaveReconnectionInterval: 3000
    failedSlaveCheckInterval: 60000
    password: null
    subscriptionsPerConnection: 5
    clientName: null
    loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 50
    slaveConnectionMinimumIdleSize: 10
    slaveConnectionPoolSize: 100
    masterConnectionMinimumIdleSize: 10
    masterConnectionPoolSize: 100
    readMode: "SLAVE"
    subscriptionMode: "MASTER"
    scanInterval: 1000
    pingConnectionInterval: 0
    keepAlive: false
    tcpNoDelay: false
    dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.SerializationCodec> {}
transportMode: "NIO"
```
