### ISSUE TITLE
Feature request: default values for YAML

### ISSUE THREAD

**Issue by aaabramov** [redisson/redisson#1922]
Support providing default values for environment variables in YAML.

For example:

```yaml
singleServerConfig:
  address: "redis://${REDIS_URL:127.0.0.1}:6379"
  timeout: ${REDIS_TIMEOUT:300}
  connectTimeout: 1000
  keepAlive: true
  pingConnectionInterval: 3000
  pingTimeout: 300
  connectionMinimumIdleSize: 2
  connectionPoolSize: 4
```

**Redisson version:**
3.10.2
