### ISSUE TITLE
org.redisson.RedissonShutdownException: Redisson is shutdown

### ISSUE THREAD

**Issue by syoukaihou** [redisson/redisson#2142]
### Expected behavior
SUCCESS

### Actual behavior
Redisson is shutdown

### Steps to reproduce or test case
```
    @Autowired
    private RedissonDistributedLocker distributedLocker;

    @Test
    public void lockTest() {

        String lockKey = "test";

        for (int i = 0; i < 50; i++) {
            Thread t = new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        System.err.println("=============线程开启============" + Thread.currentThread().getName());
                        distributedLocker.lock(lockKey, 10L); //直接加锁，获取不到锁则一直等待获取锁
                        Thread.sleep(100); //获得锁之后可以进行相应的处理
                        System.err.println("======获得锁后进行相应的操作======" + Thread.currentThread().getName());
                        distributedLocker.unlock(lockKey);  //解锁
                        System.err.println("=============================" + Thread.currentThread().getName());

                        //尝试获取锁，等待5秒，自己获得锁后一直不解锁则10秒后自动解锁
//                        boolean isGetLock = distributedLocker.tryLock(lockKey, TimeUnit.SECONDS, 1L, 10L);
//                        if (isGetLock) {
//                            Thread.sleep(5000); //获得锁之后可以进行相应的处理
//                            System.err.println("======获得锁后进行相应的操作======" + Thread.currentThread().getName());
//                            distributedLocker.unlock(lockKey);
//                            System.err.println("=============================" + Thread.currentThread().getName());
//                        }
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            });
            t.start();
        }
    }

```

### Redis version
5.0.4

### Redisson version
3.10.7

### Redisson configuration
```
# Redisson配置。支持单机，主从，哨兵，集群等模式
# 此为单机模式
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: foo
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://192.168.3.53:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec:
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO"
```
