### ISSUE TITLE
How can i merge redisson.yml and spring-application.yml

### ISSUE THREAD

**Issue by gcdd1993** [redisson/redisson#2520]
Hi, i just want to change the codec from `org.redisson.codec.FstCodec` to `org.redisson.codec.JsonJacksonCodec`,so i write the `redisson.yml`:
```yaml
codec: !<org.redisson.codec.JsonJacksonCodec> {}
```
but when i run the application, it calls exception:
```
Caused by: java.lang.IllegalArgumentException: server(s) address(es) not defined!
...
```

my `spring-application.yml` is
```yaml
spring:
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    redisson:
      config: 'classpath:/redisson.yml'
```

in `org.redisson.spring.starter.RedissonAutoConfiguration#redisson`,i find code
```java
if (redissonProperties.getConfig() != null) {
	// read config from redisson.yml
	...
} else if (redisProperties.getSentinel() != null) {
	// read config from spring-application.yml
	...
} else if (clusterMethod != null && ReflectionUtils.invokeMethod(clusterMethod, redisProperties) != null) {
	// read config from redisProperties using cluster server
	...
} else {
	// read config from redisProperties using single server
	...
}
```

so, i must write server config in `redisson.yml` again.

```yml
singleServerConfig:
  address: 'redis://127.0.0.1:6379'
  database: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
```

Is there anyway to merge  `redisson.yml` and ` spring-application.yml`?

redisson version is:
```gradle
redissonVersion = '3.11.6'
```
