### ISSUE TITLE
Unable to decode data with NullPointer

### ISSUE THREAD

**Issue by x0a1b** [redisson/redisson#2582]
**Expected behavior**
No exceptions

**Actual behavior**
Error messages from `CommandPubSubDecoder` with messages saying:
 - `Unable to decode data in separate thread: null`
 - `Unable to decode data. channel: [id: 0xdf76efe4, L:/100.112.155.17:45107 - R:master.xxx.cache.amazonaws.com/xxx.xxx.xxx.xxx:6379], reply: PooledUnsafeDirectByteBuf(ridx: 170, widx: 170, cap: 170)`

**Steps to reproduce or test case**
Use `@EnableRedissonWebSession` or `tryLockAsync` (or potentially anything that uses pubsub). Then configure redisson to decode in executor via `isDecodeInExecutor`. Under decent load it easily throws these exceptions.

**Redis version**
5.0.5

**Redisson version**
3.11.6

**Redisson configuration**
(Done pragmatically but be equivalent to this:
```
singleServerConfig:
  idleConnectionTimeout: 30000
  pingTimeout: 1000
  connectTimeout: 1000
  timeout: 1000
  retryAttempts: 3
  retryInterval: 1000
  password: null
  address: null
  subscriptionsPerConnection: 5
  clientName: MyService123
  connectionMinimumIdleSize: 16
  connectionPoolSize: 32
  database: 0
  keepAlive: true
  dnsMonitoringInterval: 60000
  isDecodeInExecutor: true
```
