### ISSUE TITLE
A lot of threads waiting on “org.redisson.spring.data.connection.RedissonConnection.sync”

### ISSUE THREAD

**Issue by littlehuihui** [redisson/redisson#2701]
When I was doing the stress test, there were more than 180 threads （like:org.redisson.spring.data.connection.RedissonConnection.write() ,OR org.redisson.spring.data.connection.RedissonConnection.read(),and org.redisson.spring.data.connection.RedissonConnection.del()）waiting for "org.redisson.spring.data.connection.RedissonConnection.sync()". What is the reason for this? And how to solve it?Thank you very much!

/*************************************************************************************************/
Code example-1
"http-nio-5201-exec-350" #677 daemon prio=5 os_prio=0 tid=0x00007f62540e1000 nid=0xbbe7 waiting on condition [0x00007f6097efa000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006e8a418d0> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:187)
	at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:227)
	at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:459)
	at org.redisson.spring.data.connection.RedissonConnection.write(RedissonConnection.java:825)
	at org.redisson.spring.data.connection.RedissonConnection.pExpire(RedissonConnection.java:418)
/*******************************************************************************************************/
Code example-2
"http-nio-5201-exec-346" #673 daemon prio=5 os_prio=0 tid=0x00007f6254030800 nid=0xbbe3 waiting on condition [0x00007f609c3ce000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006e69593d0> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at org.redisson.command.CommandAsyncService.get(CommandAsyncService.java:187)
	at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:227)
	at org.redisson.spring.data.connection.RedissonConnection.sync(RedissonConnection.java:459)
	at org.redisson.spring.data.connection.RedissonConnection.read(RedissonConnection.java:840)
	at org.redisson.spring.data.connection.RedissonConnection.hGetAll(RedissonConnection.java:1537)
	at org.springframework.data.redis.core.DefaultHashOperations.lambda$entries$13(DefaultHashOperations.java:245)
	at org.springframework.data.redis.core.DefaultHashOperations$$Lambda$1491/504979702.doInRedis(Unknown Source)

**Comment by mrniko** [comment]
Could you share your strees test code? Do you see any errors in logs?

**Comment by littlehuihui** [comment]
> Could you share your strees test code? Do you see any errors in logs?

The stress test is verified from the ERP product, no error is reported during the stress test, and the attachment is the complete thread stack。Tks
[stack.zip](https://github.com/redisson/redisson/files/4487530/stack.zip)

**Comment by mrniko** [comment]
Which Redisson version do you use?

**Comment by littlehuihui** [comment]
> Which Redisson version do you use?

3.11.2

**Comment by mrniko** [comment]
Could you try it again with version attached?

[redisson-3.12.6-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4502649/redisson-3.12.6-SNAPSHOT.jar.zip)

**Comment by littlehuihui** [comment]
> Could you try it again with version attached?
> 
> [redisson-3.12.6-SNAPSHOT.jar.zip](https://github.com/redisson/redisson/files/4502649/redisson-3.12.6-SNAPSHOT.jar.zip)

Sorry for my late response.I will validate it and update here.Thanks a million

**Comment by littlehuihui** [comment]
@mrniko 
There have been some changes from stacks, but there are still a lot of threads in the waiting and blocking state. Is there a problem with the way I use it? My redission.yaml is the default configuration.Please help me some guidance~
Thanks a lot
[ThreadDump and redissonyaml.zip](https://github.com/redisson/redisson/files/4516150/ThreadDump.and.redissonyaml.zip)

**Comment by mrniko** [comment]
Do you see any error in logs?

**Comment by littlehuihui** [comment]
> Do you see any error in logs?
No errors were found during the test.
Thanks

**Comment by mrniko** [comment]
What Redisson version do you use? Can you share Redisson config?

**Comment by littlehuihui** [comment]
> Can you share Redisson config?

The configuration information is as follows
```

---
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
  - "redis://127.0.0.1:7000"
  - "redis://127.0.0.1:7001"
  - "redis://127.0.0.1:7002"
  - "redis://127.0.0.1:7003"
  - "redis://127.0.0.1:7004"
  scanInterval: 1000
  pingConnectionInterval: 0
  keepAlive: false
  tcpNoDelay: false
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"
```
