### ISSUE TITLE
Failover with Elasticache cluster causes excessive failures, RedisNodeNotFoundException

### ISSUE THREAD

**Issue by JLP-in-SD** [redisson/redisson#2707]
**Expected behavior**
Elasticache Redis cluster failover on primary should not cause several minutes of failing Redis calls.

**Actual behavior**
After failover ClosedChannelException caused by WriteRedisConnectionException happen.
Requests timeout and fail with WriteRedisConnectionException.

Note: this looks like the same problem as issue #2678 

**Steps to reproduce or test case**
Run application
Do "failover primary" on a shard from AWS Console

**Redis version**
5.0.4

**Redisson version**
3.12.4

**Redisson configuration**
```
clusterServersConfig:
  readMode: "MASTER"
  nodeAddresses:
  - "rediss://clustercfg.redis-cluster.aaa.usw2.cache.amazonaws.com:6379"
  tcpNoDelay: "true"
```
