### ISSUE TITLE
org.redisson.tomcat.RedissonSessionManager.findSession Session can't be found

### ISSUE THREAD

**Issue by piyush55india** [redisson/redisson#2736]
Hi,

I was trying to deploy simple webapp using Redisson manager on AWS Elastic Beanstalk. The redis that I have configured, is also from AWS Elasticache.

Context.xml:
```
<Manager className="org.redisson.tomcat.RedissonSessionManager"
          configPath="${catalina.base}/conf/redisson.yml" readMode="REDIS" updateMode="DEFAULT"/>
```
redisson.yml:
```
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  address: "redis://{ClusterName}.cache.amazonaws.com:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}
transportMode: "NIO"

```

I have moved these 2 files to conf folder of Tomcat8, and also the required JARs to lib folder. If I login to box, I can see these files correctly updated in Tomcat directory.

Still when the deployment is complete, if I try to access the application, it does not come up. Even though I am able to see the war getting deployed in Tomcat.

Upon observing the logs, I saw below :

 INFO [http-nio-8080-exec-3] org.redisson.tomcat.RedissonSessionManager.findSession Session 729345036D7A8E80685303969D2DA502 can't be found

Am I making any mistake here? Redisson version is : 3.12.4
