### ISSUE TITLE
Connections are not dropped even idle time is larger than idleConnectionTimeout

### ISSUE THREAD

**Issue by stevenli1217** [redisson/redisson#2744]
connections for Redis cluster
```
7000: 17
7001: 17
7002: 67
7003: 67
7004: 17
7005: 19
```
```
d059d4385143f50065d8af39b5d1802eee23995c 127.0.0.1:7005@17005 myself,master - 0 1588375071000 14 connected 0-5460
f45784901ae916629008f28045d3f6c4c229d7b5 127.0.0.1:7002@17002 master - 0 1588375071000 16 connected 10923-16383
5bffb4061e8258210d5dab911af5028e5e9faa65 127.0.0.1:7001@17001 slave 0db7080759d155fa098516c04e442d40ec348234 0 1588375072926 15 connected
0db7080759d155fa098516c04e442d40ec348234 127.0.0.1:7003@17003 master - 0 1588375071513 15 connected 5461-10922
beebdb6edb0fcff2afbff6b9cb0e354dc489bb93 127.0.0.1:7000@17000 slave d059d4385143f50065d8af39b5d1802eee23995c 0 1588375071000 14 connected
c043ee0879b79ee4ca357237433c24897dc25ce8 127.0.0.1:7004@17004 slave f45784901ae916629008f28045d3f6c4c229d7b5 0 1588375071918 16 connected
```

For those connections to 7002/7003, I found that all of their idle time is larger than idleConnectionTimeout.   Could you please help to clarify why Redisson doesn't kill those connections?

```
$redis-cli -c -p 7002 client list | grep MyService 
id=171 addr=172.18.0.1:50020 fd=50 name=MyService age=6264 idle=6264 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly
id=172 addr=172.18.0.1:50022 fd=51 name=MyService age=6264 idle=6264 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=client
id=173 addr=172.18.0.1:50024 fd=52 name=MyService age=6264 idle=6264 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=cluster
id=174 addr=172.18.0.1:50026 fd=53 name=MyService age=6264 idle=6264 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly
id=175 addr=172.18.0.1:50028 fd=54 name=MyService age=6264 idle=6264 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly
id=176 addr=172.18.0.1:50034 fd=10 name=MyService age=6264 idle=6264 flags=r db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 obl=0 oll=0 omem=0 events=r cmd=readonly
```

My setting is as following:
```
clusterServersConfig:
  idleConnectionTimeout: 30000
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 10
  slaveConnectionMinimumIdleSize: 16
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 16
  masterConnectionPoolSize: 64

```
