### ISSUE TITLE
[JCache] IllegalStateException: Default configuration hasn't been specified

### ISSUE THREAD

**Issue by rahuldeepattri** [redisson/redisson#2980]
I have specified redisson-jcache.yaml in my resources folder. 
If I add the codec property in the configuration then get `java.lang.IllegalStateException: Default configuration hasn't been specified!
`
If I remove the codec configuration property then everything works fine.

**Expected behavior**
Config should be parsed successfully with codec property.
**Actual behavior**
Caused by: java.lang.IllegalStateException: Default configuration hasn't been specified!
	at org.redisson.jcache.JCacheManager.createCache(JCacheManager.java:118)
**Steps to reproduce or test case**
Please use the config below and run 
```
		MutableConfiguration<String, String> config = new MutableConfiguration<>();
		CacheManager manager = Caching.getCachingProvider().getCacheManager();
		Cache<String, String> cache = manager.createCache("namedCache", config);
```

Comment the codec part in config and run agian.
**Redis version**
https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/WhatIs.html
**Redisson version**
			<version>3.13.3</version>
			<artifactId>jackson-dataformat-avro</artifactId>
			<version>2.11.2</version>
            <artifactId>netty-tcnative-boringssl-static</artifactId>
            <version>2.0.31.Final</version>
  
**Redisson configuration**
```
---
clusterServersConfig:
  password: "pass"
  clientName: clisrvet
  sslProvider: OPENSSL
  keepAlive: true
  nodeAddresses:
    - "rediss://no-user-name-for-redis:pass@host:port"
codec: !<org.redisson.codec.AvroJacksonCodec> {}

```
