### ISSUE TITLE
wiki file singleServerConfig need to update 

### ISSUE THREAD

**Issue by dev-HeQian** [redisson/redisson#3191]
**Expected behavior**
run success
**Actual behavior**
with exception  Can't parse config
**Steps to reproduce or test case**

**Redis version**

**Redisson version**
redisson-spring-boot-starter:3.13.6

**Redisson configuration**
```
singleServerConfig:
  idleConnectionTimeout: 10000
#  pingTimeout: 1000 # not exist in properties
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
#  reconnectionTimeout: 3000 # not exist in properties
#  failedAttempts: 3 # not exist in properties
  password:
  subscriptionsPerConnection: 5
  clientName: yitu
  address: redis://127.0.0.1:6379
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
#  dnsMonitoring: false # not exist in properties
  dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: NIO
```
