### ISSUE TITLE
Fill variables in redisson.yml with Spring Boot values.

### ISSUE THREAD

**Issue by broodjetom** [redisson/redisson#3206]
**Is your feature request related to a problem? Please describe.**

We are using redisson-spring-boot-starter. We were hoping that we could configure Redisson with a couple of fixed values through a configuration file and reference that from our application.yml: 

```
spring:
  redis:
    redisson: 
      file: classpath:redisson.yaml
```

Then some more dynamic values set that in the application.yml itself:

```
spring:
  redis:
    host: ${REDIS_HOSTNAME}
```

With a Spring Boot of "local" it would be

```
spring:
  redis:
    host: localhost
```

That way we would be able to have different configurations for our local run configuration with what we use in our production systems.

**Describe the solution you'd like**

If the merging of application.yml(or application-local.yml) with redisson.yml is not possible, can we then maybe have some feature where we fill variables with Spring Boot values. That way the redisson.yml would be able to look like:

```
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  subscriptionsPerConnection: 5
  address: "redis://${REDIS_HOSTNAME}:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 10
  connectionPoolSize: 64
  dnsMonitoringInterval: 5000
```

In such a way, we would be able to create an application-local.yml that looks like this: 

```
REDIS_HOSTNAME: localhost
```

With Spring Boot values I mean the values described by externalized configuration [here](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config). That way there are many ways to inject variables into the configuration of Redisson.

**Describe alternatives you've considered**

We currently are using the following as an application.yml:

```
spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          subscriptionsPerConnection: 5
          address: "redis://${ELASTICACHE_URL}:6379"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 10
          connectionPoolSize: 64
          dnsMonitoringInterval: 5000
```

This works for us but puts a lot of detail for a specific dependency in the application.yml. These fields are never changed. The values are prone to mistakes.

**Comment by broodjetom** [comment]
I would like to implement this, but I need some more guidance from the maintainers. In the documentation of redisson-spring-boot-starter it states that you can use "Common Spring Boot settings" or "Redisson settings". It would be nice if we can use both and merge them in some order. Or we can add some additional documentation about how the settings are prioritized (Redisson settings at the moment).

We can use common Spring Boot settings to setup Redisson:

```yaml
spring:
  redis:
    secure: false
    host: localhost
    port: 6379
---
spring:
  redis:
    url: redis://localhost:6379
```

We can achieve the same with Redisson settings:

```yaml
spring:
  redis:
    redisson: 
      config: |
        singleServerConfig:
          address: redis://localhost:6379
---
spring:
  redis:
    redisson: 
      # Put the configuration into seperate file:
      file: classpath:redisson.yaml
```

The common Spring Boot settings allow us to dynamically (via externalized configuration) set the properties for Redisson. But there are limitations: there is only a small set of properties we can set with the common Spring Boot settings, described in `org.springframework.boot.autoconfigure.data.redis.RedisProperties`.

The Redisson settings do **not** allow us to dynamically (via externalized configuration) set the properties for Redisson. But it also adds a lot of more possibilities. Just take a look at some of the server configurations (ClusterServersConfig, SingleServerConfig) that are available. These configuration let us configure Redisson very precisely, something that is not possible with the common Spring Boot settings.

Can we combine the best of the two settings options: externalized configuration _and_ precise configuration?

I am thinking of the different possibilities: the seperate file for redisson.yaml is nice, but is there some Spring Boot method to include that file into the application configuration? Could we maybe add an additional field to the RedissonProperties so that we more options than only a block (starting with "|") or a file? 

Also what should the priority be in merging: The common Spring Boot settings, the Redisson settings. And in turn of Redisson settings, what should overwrite what? We could have file, config, and maybe an additional field.
