### ISSUE TITLE
Can we share sharing the same Redisson client for both Hibernate L2 cache and Spring Cache Abstraction

### ISSUE THREAD

**Issue by ManeeshSharma17** [redisson/redisson#3212]
Can we share sharing the same Redisson client for both Hibernate L2 cache and Spring Cache Abstraction? 
I am configuring redisson as my l2 cache in application.propeties 
```
  region:
    factory_class: org.redisson.hibernate.RedissonRegionFactory
  redisson:
    config: redisson.json
```

Currently, I am creating a Cache manager bean using the below code, which creates a new connection to redis.
```
    @Bean
    public RedissonClient redissonClient() throws IOException {
        Resource resource = resourceLoader.getResource("classpath:/" + redissonConfigFile);
        Config config = Config.fromYAML(resource.getInputStream());
        return Redisson.create(config);
    }

    @Bean
    public CacheManager cacheManager(RedissonClient redissonClient) {
        return new RedissonSpringCacheManager(redissonClient);
    }
```
I want to create a Cache Manager bean use the same connection configured in application properties. Is it possible to do that?
