### ISSUE TITLE
How to configure checksentinelslist in springboot file

### ISSUE THREAD

**Issue by jiangqp15** [redisson/redisson#3230]
How to configure checksentinelslist in springboot file

**Comment by mrniko** [comment]
Here is an example:

```yaml
  redisson: 
    config: |
      sentinelServersConfig:
        checkSentinelsList: false
      threads: 16
      nettyThreads: 32
```
