### ISSUE TITLE
Why does the first IP of the cluster automatically change to the intranet IP?

### ISSUE THREAD

**Issue by HeyChiang** [redisson/redisson#3304]
This is my configration file
```yml
spring:
  redis:
    timeout: 10000
    cluster:
      nodes:
        - 120.79.8.153:7000
        - 120.79.8.153:7001
        - 120.79.8.153:7002
        - 120.79.8.153:7003
        - 120.79.8.153:7004
        - 120.79.8.153:7005
```
This is my log. note that the ip of port 7000 has changed,
```log
a0eb8a93e3ce9a3ac2d15c73a9d8c3bf7064904d 120.79.8.153:7002@17002 master - 0 1608603104000 3 connected 10923-16383
dfc494ff70a7b10af271a8e132899c47e771fecc 120.79.8.153:7004@17004 slave 20e35d1e53f766ae93a7158f5e8ff4ac379ef8a0 0 1608603105000 1 connected
422579dc30a3aa20cc2cc2e119f893691dcfdca7 120.79.8.153:7005@17005 slave 645a4f040a4bb12b91aa52c23373c4b5acc7c84b 0 1608603105945 2 connected
20e35d1e53f766ae93a7158f5e8ff4ac379ef8a0 172.18.40.70:7000@17000 myself,master - 0 1608603106000 1 connected 0-5460
c295c0f4b6bac3cc3b883e73dd53826cb9a48204 120.79.8.153:7003@17003 slave a0eb8a93e3ce9a3ac2d15c73a9d8c3bf7064904d 0 1608603104944 3 connected
645a4f040a4bb12b91aa52c23373c4b5acc7c84b 120.79.8.153:7001@17001 master - 0 1608603106947 2 connected 5461-10922
```
When I test the code on my computer, I always get an error: Can't connect to master: redis://172.18.40.70:7000 with slot ranges: [[0-5460]]
