### ISSUE TITLE
Get value failed in cluster mode

### ISSUE THREAD

**Issue by lvsj** [redisson/redisson#3328]
**redisson dependency : redisson-spring-boot-starter , version: 3.14.0**
**redisson config**
``` yml
spring:
  application:
    name: spring-boot-demo
  redis:
    database: 0
    password: 80e6eaab67dc5b8fef5f585d8f289e54
    cluster:
      nodes:
        - 172.21.22.22:9000 
        - 172.21.22.22:9001
        - 172.21.22.86:9000
        - 172.21.22.86:9001
        - 172.21.22.83:9000
        - 172.21.22.83:9001
 ```
Both redis in 172.21.22.22 are slave , when there is  one key in 9000‘redis and  one key in 9001`redis,   failed to get key in 9000'redis by RedisTemplate.
