### ISSUE TITLE
Repeat consumption(multiple listeners)

### ISSUE THREAD

**Issue by fengyu-ssw** [redisson/redisson#3369]
#### redisson version

```xml
<dependency>
    <groupId>org.redisson</groupId>
    <artifactId>redisson-spring-boot-starter</artifactId>
    <version>3.14.0</version>
</dependency>
```

#### config

```java
@Bean
RedisMessageListenerContainer container(RedisConnectionFactory redisConnectionFactory) {
    RedisMessageListenerContainer container = new RedisMessageListenerContainer();
    container.setConnectionFactory(redisConnectionFactory);

    container.addMessageListener(new MyListener(), new PatternTopic("__keyspace@0__:mykey"));
    container.addMessageListener(new MyListener(), new PatternTopic("__keyevent@0__:del"));
    return container;
}

static class MyListener implements MessageListener {
    @Override
    public void onMessage(Message message, byte[] pattern) {
        printMsg("my custom", message);
    }
}

public static void printMsg(String prefix, Message message) {
    System.out.println(prefix + " -> body: " + new String(message.getBody()));
    System.out.println(prefix + " -> channel: " + new String(message.getChannel()));
}
```

#### test

```java
@Test
public void test02(){
    redisTemplate.opsForValue().set("mykey", "2");
    redisTemplate.delete("mykey");
    String next = new Scanner(System.in).next();
}
```

#### When not using reidsson

```Plaint Text
my listener -> body: set;  channel: __keyspace@0__:mykey
my listener -> body: del;  channel: __keyspace@0__:mykey
my listener -> body: mykey;  channel: __keyevent@0__:del
```

#### use redisson
- How can I get the same result as above?
```Plaint Text
my listener -> body: set;  channel: __keyspace@0__:mykey
my listener -> body: set;  channel: __keyspace@0__:mykey
my listener -> body: del;  channel: __keyspace@0__:mykey
my listener -> body: mykey;  channel: __keyevent@0__:del
my listener -> body: mykey;  channel: __keyevent@0__:del
my listener -> body: del;  channel: __keyspace@0__:mykey
```

**Comment by mrniko** [comment]
can you share Redisson config?

**Comment by fengyu-ssw** [comment]
#### application.yml

```yaml
spring:
  redis:
    redisson:
      config: classpath:redisson.yml
    database: 0
    host: 175.24.191.39
    port: 8001
    password:
    timeout: 1000
    lettuce:
      pool:
        max-idle: 8
        max-wait: -1
        min-idle: 0
        max-active: 8
```



#### redisson.yml

```yaml
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  #  reconnectionTimeout: 3000
  #  failedAttempts: 3
  password:
  subscriptionsPerConnection: 5
  clientName: null
  address: redis://ksy.zone:8001 # 175.24.191.39
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 32
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 2
nettyThreads: 2
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode : "NIO"
```
