### ISSUE TITLE
Redis cluster master restart cause tps down and can't recover

### ISSUE THREAD

**Issue by tony1991** [redisson/redisson#3407]
**Expected behavior**
Redis cluster master down, redisson client update cluster state, and tps come down.  After a period of time, restart master node,  tps come back to normal.

**Actual behavior**
restart master node,  tps  can't recover , just come back a little.  And server no error.

**Steps to reproduce or test case**
5 master and 5 slave
master 1 down and wait for slave become master
restart master 1,  observe tps

```
config
    readMode: "MASTER"
    subscriptionMode: "MASTER"
    nodeAddresses:
        - "redis://127.0.0.1:7001"
        - "redis://127.0.0.1:7002"
        - "redis://127.0.0.1:7003"
        - "redis://127.0.0.1:7004"
        - "redis://127.0.0.1:7005"
        - "redis://127.0.0.1:7006"
        - "redis://127.0.0.1:7007"
        - "redis://127.0.0.1:7008"
        - "redis://127.0.0.1:7009"
        - "redis://127.0.0.1:7010"
    scanInterval: 1000
    failedSlaveReconnectionInterval: 3000
    failedSlaveCheckInterval: 3000
    pingConnectionInterval: 5000
```

**version**
redisson version : 3.14.1

Looking forward for your response, Thank you!
