### ISSUE TITLE
redisson config lead to The remote host forced an existing connection to close.

### ISSUE THREAD

**Issue by wenming5112** [redisson/redisson#3454]
**Expected behavior**

**Actual behavior**
After a few minutes of redis operation, the following problems will appear:
The remote host forced an existing connection to close.

**Steps to reproduce or test case**

**Redis version**

**Redisson version**
```xml
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-actuator</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.redisson</groupId>
            <!-- for Spring Data Redis v.2.3.x -->
            <artifactId>redisson-spring-data-23</artifactId>
        </dependency>
```

**Redisson configuration**

```java
    @Bean
    public RedissonClient redissonClient() {
        Config config = new Config();
        config.useSingleServer()
                .setAddress("redis://192.168.1.1:6379")
                .setPassword("123456");
        return Redisson.create(config);
    }
```

- my redis config 
```yml
spring:
  ### redis
  redis:
    host: 192.168.1.1
    database: 0
    port: 6379
    password: 123456
    # 连接超时时间
    timeout: 2000ms
    jedis:
      pool:
        # 最大连接数
        max-active: 2000
        # 最大阻塞等待时间(负数表示没限制)
        max-wait: 1000ms
        # 最大空闲
        max-idle: 8
        # 最小空闲
        min-idle: 5
```
