### ISSUE TITLE
How to use name mapper in yaml config?

### ISSUE THREAD

**Issue by wltj920** [redisson/redisson#3597]
Thanks for nameMapper feature.

My application has multiple environments, dev environment use single server config, prod environment use cluster server config. The SpringBoot app use `spring.profiles.active` property to change env.

I need to set same nameMapper, but how can I write the config in yaml file?

that is my yaml file:

```yaml
spring:
  redis:
    lettuce: # lettuce连接池配置，线程安全
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
    redisson:
      # 官方文档：https://github.com/redisson/redisson/wiki/2.-Configuration
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 60000 # 默认为3秒，改为60秒
          retryAttempts: 3
          retryInterval: 1500
          password: "it56&*Redis"
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://192.168.206.166:6379"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 0
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
```

**Comment by mrniko** [comment]
Here is the example:

```yaml
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 60000 # 默认为3秒，改为60秒
          retryAttempts: 3
          retryInterval: 1500
          nameMapper: !<org.domain.MyMapper> {}
```
