### ISSUE TITLE
Redisson mget性能问题

### ISSUE THREAD

**Issue by yazifs** [redisson/redisson#3726]
你好，我们在压测过程中，发现在服务器cpu使用率为90左右%时，Redisson性能有不稳定问题，随着压测时间的增加，TPS会逐步下降，主要的耗时在`redisTemplate.opsForValue().multiGet(keys)`上，耗时最大可达7s以上，dump堆内存后，发现`RedisConnection`个数并没有增加，依旧保持最小连接数在运行，压测期间，我们尝试调整过`threads`、`readMode`、`nettyThreads`均没有明显效果，将驱动更换为Jedis后，该现象并没有出现。Redisson遇到这个问题需要调整什么参数解决？
下面是我们的测试场景，及结果：
```java

    @Autowired
    private final RedisTemplate<String, Object> redisTemplate;


   /**
     * 部分代码已省略，仅保留核心代码
     *
     * @param keys
     * @param cacheLoader
     * @return
     */
    public List<Object> get(List<String> keys, CacheLoader<List<String>, List<Object>> cacheLoader) {

        // load from redis
        final List<Object> remoteCachedResult = redisTemplate.opsForValue().multiGet(keys);

        BitSet missIndex = new BitSet(keys.size());

        // find miss key
        List<String> missKey = new ArrayList<>();
        for (int i = 0; i < keys.size(); i++) {
            if (remoteCachedResult.get(i) == null) {
                missKey.add(keys.get(i));
                missIndex.set(i);
            }
        }

        // load miss key if necessary
        if (CollectionUtils.isNotEmpty(missKey)) {
            final List<Object> load = cacheLoader.load(missKey);

            int keyIndex = -1;
            for (Object t : load) {
                keyIndex = missIndex.nextSetBit(keyIndex + 1);
                if (t != null) {
                    redisTemplate.opsForValue().set(keys.get(keyIndex), t);
                    remoteCachedResult.set(keyIndex, t);
                }
            }
        }
        return remoteCachedResult;
    }


```
* Redisson:
![Redisson](https://user-images.githubusercontent.com/23451518/125225492-fd5af080-e301-11eb-9ceb-3a41f44fe21d.png)
* Jedis
![jedis](https://user-images.githubusercontent.com/23451518/125225605-29767180-e302-11eb-8f43-e918344af29e.png)

* 版本
  * Redisson: 3.16.0
  * redisson-spring-data: 3.16.0
  * springboot: 1.5.22
  * redis: 4.0（集群部署，3主3从）
* 配置
```yaml
    redisson:
      config: |
        clusterServersConfig:
          readMode: MASTER_SLAVE
          connectTimeout: 1000
          retryAttempts: 3
          retryInterval: 1500
          failedSlaveReconnectionInterval: 1500
          failedSlaveCheckInterval: 30000
          password: password
          slaveConnectionMinimumIdleSize: 64
          slaveConnectionPoolSize: 256
          masterConnectionMinimumIdleSize: 64
          masterConnectionPoolSize: 256
          nodeAddresses:
          - "redis://ip:port"
          - "redis://ip:port"
          - "redis://ip:port"
          - "redis://ip:port"
          - "redis://ip:port"
          - "redis://ip:port"
        threads: 256
        nettyThreads: 0
```
