### ISSUE TITLE
Hostname ends up comparing against IP address

### ISSUE THREAD

**Issue by ghollies** [redisson/redisson#3819]
**Expected behavior**
When using redis and sentinel in hostname mode, when redis and sentinel instances are restarted, the redisson client should allow its known slaves to reconnect to the same master.

**Actual behavior**
Redisson is comparing the hostname to a saved IP address and not realized it is the same.

**Steps to reproduce or test case**

Redis deployed into K8s using the following settings:
```
replica-announce-ip <hostname>
sentinel announce-ip <hostname>
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
```

**Redis version**
6.0.15

**Redisson version**
9a7eb2ea14e4104984bb03d58d1a0dfc84e05636  (3.16.2-SNAPSHOT taken after the linked issue was merged)

**Redisson configuration**
```
sentinelServersConfig:
  sentinelAddresses:
    - "redis://${REDIS_SENTINEL_SVC}:26379"
  username: "${REDIS_USER}"
  password: "${REDIS_PASSWORD}"
  sentinelPassword: "${REDIS_SENTINEL_PASSWORD}"
  masterName: mymaster
codec: !<org.redisson.codec.SerializationCodec> {}
```

Setup:
3 redis + 3 sentinel (running in a Kubernetes cluster), kill off 2 pairs of redis/sentinels pods (redis master and a replica)
the pods come back with different IP address sometimes (but not always) and they a
Redis returns to a healthy state, but running into issues where the client can't recover.

One issue is that replicas coming back are not being considered having the same master

![image](https://user-images.githubusercontent.com/5289168/131872262-ec25c4eb-59ee-4d9c-94b2-bca8a3636705.png)
We can see here that the SentinelConnectionManager thinks current master is `100.64.110.145` while the replica is reporting its master as `redis-node-1`'s hostname

they both point to the same instance, but the comparison is not working correctly. 
![image](https://user-images.githubusercontent.com/5289168/131873886-d0bb5141-6cc3-4c8f-8456-608c1c2a0b5d.png)

I'm not sure yet if its caused by the same comparison issue, when killing and recreating the pod which was running the master redis node, we are running into a state where the `ClientConnectionsEntry` for `MASTER` is marked as frozen, even after it should have been working. I think it may be a timing issue with the unfreeze call during re-connection, but still working on isolating it. (if i manually unfreeze the master entry via remote debugging, it starts to work again)
![image](https://user-images.githubusercontent.com/5289168/131895092-a2f8d051-de4c-4374-b4e6-0d143e9bc31c.png)
