### ISSUE TITLE
[question] 3 node SENTINEL init fails with "SENTINEL SENTINELS command returns less than 2 nodes"

### ISSUE THREAD

**Issue by wo3930** [redisson/redisson#3824]
> SENTINEL SENTINELS command returns less than 2 nodes! At least two sentinels should be defined in Redis configuration. Set checkSentinelsList = false to avoid this check.

Any idea why this could happen

```
spring:
  redis:
    ssl: false
    lettuce:
      pool: 
        maxActive: 100      
        maxIdle: 10         
        maxWait: 30000       
    timeout: 15000
    password: xxxx
    sentinel:
      master: local-master
      nodes: ip1:26379,ip1:26380,ip1:26381
```
note：redisson version 3.15.0
