### ISSUE TITLE
如何使用 jasypt 加密配置

### ISSUE THREAD

**Issue by linyongfu2013** [redisson/redisson#3831]
`redisson` 的配置好像无法使用 `jasypt` 进行加密解密？

**Comment by linyongfu2013** [comment]
使用单独的`redisson.yml` 无法使用`jasypt`加密解密，而写在`application.yml` 则可以
```
spring:
  redis:
    database: 2
    host: 127.0.0.1
    port: 1234
    password: ENC(NPWxPDc4zQeCLUnv/iHez2TkBdc/WZjd)
    lettuce:
      pool:
        min-idle: 1
        max-idle: 5
        max-active: 20
        max-wait: 60000
    redisson:
#      file: "classpath:redisson-dev.yml"
      config:
        singleServerConfig:
          address: "redis://127.0.0.1:1234"
          password: ENC(NPWxPDc4zQeCLUnv/iHez2TkBdc/WZjd)
          database: 2
        threads: 0
        nettyThreads: 0
        codec:
          class: "org.redisson.codec.JsonJacksonCodec"
        transportMode: NIO
```

但是这样又出现另外一个问题，就是序列化变成了二进制，配置的序列化方式不起作用了。
另外，文档写的默认的序列化是`JsonJacksonCodec`，但我实测并不是啊，默认用的还是二进制方式。
