### ISSUE TITLE
Netty memory leak error

### ISSUE THREAD

**Issue by T00fy** [redisson/redisson#3884]
Hey, I saw a few other similar posts already but they weren't this exact error. I am running version 3.16.3.

I am using AWS elasticache with a replicated server setup in cluster mode and am only really using redisson to try and store sessions.

Context.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<Context path="/app">

    <Valve className="org.apache.catalina.valves.PersistentValve" />

    <Manager className="org.redisson.tomcat.RedissonSessionManager"
             configPath="/usr/local/tomcat/conf/redisson.conf"
             readMode="REDIS" updateMode="DEFAULT" broadcastSessionEvents="false"
             keyPrefix="" />
```

redisson.conf
```
replicatedServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
  - "redis://app.cache.amazonaws.com:6379" //not the real address
  scanInterval: 1000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.MarshallingCodec> {}
transportMode: "NIO"
```

The below is the stack trace I get, it happens while tomcat is starting up.

```
12-Oct-2021 16:22:07.359 SEVERE [redisson-netty-2-28] io.netty.util.ResourceLeakDetector.reportTracedLeak LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
Created at:
	io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:402)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:188)
	io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:174)
	io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:108)
	org.redisson.codec.MarshallingCodec.lambda$new$1(MarshallingCodec.java:156)
	org.redisson.command.CommandAsyncService.encodeMapValue(CommandAsyncService.java:734)
	org.redisson.RedissonObject.encodeMapValue(RedissonObject.java:310)
	org.redisson.RedissonMap.putAllOperationAsync(RedissonMap.java:796)
	org.redisson.RedissonMap.putAllAsync(RedissonMap.java:737)
	org.redisson.RedissonMap.putAll(RedissonMap.java:674)
	org.redisson.tomcat.RedissonSession.save(RedissonSession.java:427)
	org.redisson.tomcat.RedissonSessionManager.add(RedissonSessionManager.java:221)
	org.apache.catalina.session.StandardSession.setId(StandardSession.java:358)
	org.apache.catalina.session.StandardSession.setId(StandardSession.java:342)
	org.apache.catalina.session.ManagerBase.createSession(ManagerBase.java:689)
	org.redisson.tomcat.RedissonSessionManager.createSession(RedissonSessionManager.java:132)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
```

There are a few other redisson-netty errors with similar stacktraces - all seems to be related to the Servlet filters on my application
