### ISSUE TITLE
Redisson connection uses unsafe.Allocatememory() cause direct memory leak

### ISSUE THREAD

**Issue by caizy-2020** [redisson/redisson#3945]
Hey,

In the production environment, we found that the memory occupied by the program has been increasing. Using the `top` command, we found that the value of `RES `has been increasing, even exceeding `Xmx`. We use `jconsole.exe `to observe that the number of threads and classes is stable, and the size of heap memory and meta space are within the normal range. Therefore, **we begin to suspect that the program is constantly occupying native memory and is not released.**

When we use `gperftools `to analyze the memory allocation occupied by the program, we will find that the method unsafe.Allocatememory0 occupies a very large proportion of memory and increases over time. 

![image](https://user-images.githubusercontent.com/65394715/141609235-184610ca-3bb6-4b0c-9840-3ba77ee76662.png)
![image](https://user-images.githubusercontent.com/65394715/141609283-0cafa3b4-b4c5-4f94-957b-b36660990898.png)

This is the original PDF file generated using gperftools analyzer memory
[redisson-demo_1318.pdf](https://github.com/redisson/redisson/files/7531676/redisson-demo_1318.pdf)
[redisson-demo_1450.pdf](https://github.com/redisson/redisson/files/7531677/redisson-demo_1450.pdf)

After debugging with debug, it is found that the thread `redisson-netty` calls `unsafe.Allocatememory()`.

![20211010132457(1)](https://user-images.githubusercontent.com/65394715/141610539-1c0cff1e-ccc6-44db-9829-91f8e9f96425.png)

After modifying the redisson configuration so that redisson is no longer used to connect to redis, we use `gperftools `to observe that there is no Unsafe_AllocateMemory0, and the memory occupied by the program remains stable and will not increase,**so we now suspect that redisson caused the program's native memory leak**

**Expected behavior**
We hope to get your help so that we can use redisson without increasing the memory all the time

**My environment**
redis `5.0.12`
redisson `3.12.4`
springboot `2.4.2`
openjdk `version "11" 2018-09-25`

redisson config
```
redisson:
  address: redis://127.0.0.1:6379
  password: ''
  threads: 32
  nettyThreads: 100
  connectionPoolSize: 100
  masterConnectionMinimumIdleSize: 10
  slaveConnectionPoolSize: 100
  slaveConnectionMinimumIdleSize: 10
  masterConnectionPoolSize: 100
  connectionMinimumIdleSize: 10
  bloomfilterDefaultExpectedInsertions: 1000
  bloomfilterDefaultFalseProbability: 0.05
```

**Steps to reproduce or test case**
[redisson_demo.zip](https://github.com/redisson/redisson/files/7531565/redisson_demo.zip)

1. unzip redisson_ demo.zip
2. modify start.sh to set your redis address
3. execute start.sh to start the jar
