### ISSUE TITLE
Redisson doesn't support username for sentinels 

### ISSUE THREAD

**Issue by mmorel-35** [redisson/redisson#3948]
**Expected behavior**
Redisson shall be able to support sentinel authentication. 
Maybe a sentinelUsername shall suffice. 

**Actual behavior**
Only the sentinel Password is used for authentication 

**Steps to reproduce or test case**

**Redis version**
6.2.6
**Redisson version**
3.16.4
**Redisson configuration**

```yaml
username:  "myserusername"
password: "myserverpassword"
...
sentinelPassword: "mysentinelpassword"
```
