### ISSUE TITLE
Config readMode from SLAVE but redirect to MASTER

### ISSUE THREAD

**Issue by billhcmus** [redisson/redisson#4040]
**Expected behavior**

- The Lua script executes on the Slave node

**Actual behavior**

- The Lua script executes on the Master node

**Steps to reproduce or test case**

Here is the Java code:
```java
redissonClient
          .getScript()
          .evalSha(
              RScript.Mode.READ_ONLY,
              "<sha1-hash>",
              RScript.ReturnType.MULTI,
              getKeys(),
              getArgs());
```

Here is the Lua script

```lua
local id = redis.call("CLUSTER", "MYID")

redis.log(redis.LOG_NOTICE, "I'm get master account " .. id)
return redis.call('hmget', KEYS[1], unpack(ARGV))
```

After executing Java code and the Redis's log like bellow

<img width="1440" alt="Screen Shot 2021-12-21 at 21 39 45" src="https://user-images.githubusercontent.com/16277024/146949493-82c77dc0-0e0d-484d-9524-08bac7047c75.png">

We can see that the Lua script is executed on the master node (127.0.0.1:7001) instead of the slave node (127.0.0.1:7005), but I have already config the readMode to SLAVE & pass the RScript.Mode.READ_ONLY config when evalSha.

Please help me correct if I'm wrong, thanks!

**Redis version**

v6.2.0

**Redisson version**

v3.16.2

**Redisson configuration**

```yaml
  redissonConfig:
    clusterServersConfig:
      idleConnectionTimeout: 10000
      pingTimeout: 1000
      connectTimeout: 3000
      timeout: 5000
      retryAttempts: 2
      retryInterval: 100
      failedSlaveReconnectionInterval: 3000
      failedSlaveCheckInterval: 60000
      password: null
      subscriptionsPerConnection: 5
      clientName: null
      subscriptionConnectionMinimumIdleSize: 1
      subscriptionConnectionPoolSize: 10
      slaveConnectionMinimumIdleSize: 1
      slaveConnectionPoolSize: 1
      masterConnectionMinimumIdleSize: 1
      masterConnectionPoolSize: 4
      readMode: "SLAVE"
      subscriptionMode: "MASTER"
      scanInterval: 1000
      pingConnectionInterval: 1000
      keepAlive: true
      tcpNoDelay: true
      nodeAddresses:
        - "redis://127.0.0.1:7000"
        - "redis://127.0.0.1:7001"
        - "redis://127.0.0.1:7002"
        - "redis://127.0.0.1:7003"
        - "redis://127.0.0.1:7004"
        - "redis://127.0.0.1:7005"
    threads: 128
    nettyThreads: 128
```
