### ISSUE TITLE
Redisson requires reflect-config to run

### ISSUE THREAD

**Issue by romilpunetha** [redisson/redisson#4173]
I have a `LockFactory` class which provides the `default` and `multilock`. The following code results in a bad request with no logs at all:

```
public Uni<Void> test() {
        Lock lock = lockFactory.getLock("test Lock");
        return lock.acquire()
                .invoke(() -> Log.debug("\n\n\nLockAcquired : " + lock + "\n\n\n"))
                .eventually(lock::release);
    }
```

application.json

```
quarkus:
  redisson:
    cluster-servers-config:
      nodeAddresses: ${REDIS_HOSTS}
```

In normal mode and in native mode locally, I see redisson logs. However, when I deploy the native build, I don't see a single redisson log. Any ideas what might be happening here?
