### ISSUE TITLE
Client suddenly spikes in latency and then does not recover until Redisson connections are reset

### ISSUE THREAD

**Issue by nathanielhsu** [redisson/redisson#4224]
### Expected behavior
Redisson client should not all of a sudden have persistent latency spikes

### Actual behavior
Every so often, I see latency for GETs all of a sudden spike up from ~4ms to well over 100ms and then stay there until I reset the connections to cache by doing a forced deployment on the application to create new Redis connections. I see this behavior several times every week. See screenshot below for latency spike which recovers only after connections have been reset: 
![Screen Shot 2022-04-11 at 6 02 49 PM](https://user-images.githubusercontent.com/12907522/162857779-11db2444-3aa8-467f-b3e7-3ea95a0e8cbf.png)

When checking the logs, I found a bunch of the following error: `org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (20 ms) occured after 1 retry attempts. Increase nettyThreads and/or timeout settings.`

For our use case, since latency is a priority, we don't want to set the response timeout much higher than this or have too many retry attempts. At the same time though, timeout aside, we shouldn't be seeing such long lasting latency impact here.

I'm currently using Redisson version 3.16.3 with [this fix mentioned here](https://github.com/redisson/redisson/issues/3871#issuecomment-943176694) and this is the Redisson configuration:
```
ClusterModeEnabled: true
ReadMode: Slave
TimeoutMilliSeconds: 100
RetryAttempts: 3
RetryIntervalMilliSeconds: 100
MasterConnectionMinimumIdleSize: 2
MasterConnectionPoolSize: 2
ReplicaConnectionPoolSize = 24
ReplicaConnectionMinimumIdleSize: 24
PingConnectionInterval: 1000
FailedSlaveReconnectionInterval: 3000
FailedSlaveCheckInterval: 5000
```

We are using batched get calls with `org.redisson.api.BatchOptions` with the following configuration:
```
TimeoutMilliSeconds: 20
RetryAttempts: 1
RetryIntervalMilliSeconds: 3
```

Another thing to note is that when this issue happens, it happens only on 1 or 2 Redis nodes, so it seems to be all the channels connected to those tasks going bad all at once and then not recovering.

Two questions here:
1. I just want to understand why this is happening in the first place. Why is it that all of a sudden, we will see a sudden jump in latency that stays high until connections are reset. Is this just a channel going bad? And if that's the case, why isn't Redisson client recovering quickly from the bad channel? From investigation, this doesn't seem to be related to TPS at all.
2. Could this be related to our configuration settings? And if not, is this a bug in Redisson client? I've checked with Elasticache/Redis support and they've confirmed that there's no underlying problem with the Redis cluster/node.

Any help or direction here would be appreciated. Thanks!

**Comment by micr0farad** [comment]
same issue for me after azure redis failover

**Comment by mrniko** [comment]
> I found a bunch of the following error: org.redisson.client.RedisResponseTimeoutException: Redis server response timeout (20 ms) occured after 1 retry attempts. Increase nettyThreads and/or timeout settings.

Are these errors occur until the application redeployment?

**Comment by mrniko** [comment]
@micr0farad 

Which Redisson version?

**Comment by micr0farad** [comment]
@mrniko which error stacktraces? My services experience increase of latency on any redis query after redis cluster failover. Redis client settings are following: 
```
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 128
  readMode: "MASTER"
  subscriptionMode: "SLAVE"
  scanInterval: 1000
  pingConnectionInterval: 3000
  keepAlive: true
  tcpNoDelay: true
checkLockSyncedSlaves: false
threads: 16
nettyThreads: 128
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"
```
