### ISSUE TITLE
Migrated slave client connections on the master node upon corresponding slave failure are not released after the slave node recovered

### ISSUE THREAD

**Issue by RunzhongHuang** [redisson/redisson#4354]
Hi Redisson Community,

While testing the client connection amount that redisson client establish, I notice three behaviors that I don't have an answer about. Might be a connection leak, but I don't know if there is any reason. Hope anyone could share some hint about the reason behind the scene.

#### Redisson client version
v3.17.3

#### Code I use for the behavior below
```
//Only using the initialization, no any query is performed

public class RedissonTest {

    public static void main(String[] args) throws Exception {

        File redissonConfigYaml = new File("<path>/redisson.yaml");
        Config redissonConfig = Config.fromYAML(redissonConfigYaml);

        if (Epoll.isAvailable()) {
            redissonConfig.setTransportMode(TransportMode.EPOLL);
        }

        RedissonClient redissonClient = Redisson.create(redissonConfig);
    }
}
```

#### Redisson configuration I use
```
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: null
  subscriptionsPerConnection: 5
  clientName: Test
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 0
  subscriptionConnectionPoolSize: 0
  slaveConnectionMinimumIdleSize: 2
  slaveConnectionPoolSize: 2
  masterConnectionMinimumIdleSize: 2
  masterConnectionPoolSize: 2
  readMode: "MASTER_SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - "redis://redis.master1:6359"
    - "redis://redis.master2:6359"
    - "redis://redis.master3:6359"
  scanInterval: 5000
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: false
threads: 2
nettyThreads: 32
codec: !<org.redisson.codec.FstCodec> {}

transportMode: "NIO"
```

#### 1\. Extra client connection in master nodes

When I initialize the redisson client, I ran the `client list` command to list all the client connections with name "Test" (defined in the configuration above). And I expect 2 connections to each master node, and 2 connections to each slave node. But instead, I saw **3 connections to each master node**, and 2 connections to each slave node.

Below are the 3 client connections I captured in different time. And I noticed one of the connection is doing cmd "cluster" sometime.
```
id=190 addr=localhost:1852 laddr=redis.master1:6359 fd=20 name=Test age=12 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20504 events=r cmd=cluster user=default redir=-1
id=191 addr=localhost:1854 laddr=redis.master1:6359 fd=21 name=Test age=12 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
id=192 addr=localhost:1855 laddr=redis.master1:6359 fd=22 name=Test age=12 idle=12 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
```

```
id=190 addr=localhost:1852 laddr=redis.master1:6359 fd=20 name=Test age=36 idle=6 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
id=191 addr=localhost:1854 laddr=redis.master1:6359 fd=21 name=Test age=36 idle=6 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
id=192 addr=localhost:1855 laddr=redis.master1:6359 fd=22 name=Test age=36 idle=6 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
```

```
id=190 addr=localhost:1852 laddr=redis.master1:6359 fd=20 name=Test age=126 idle=5 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
id=191 addr=localhost:1854 laddr=redis.master1:6359 fd=21 name=Test age=126 idle=5 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
id=192 addr=localhost:1855 laddr=redis.master1:6359 fd=22 name=Test age=126 idle=5 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=0 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=20496 events=r cmd=ping user=default redir=-1
```

I am guessing that the extra connection is remained for resolving the topology, but I am not 100% sure. So may I ask what is the purpose of the extra connection on master node? 

If there is a purpose for the extra connection, is this extra connection not limited by the pool size from the configuration (I set both connection pool size minimum and limit to 2)?

#### 2\. Upon slave node failure, the connections are migrated to master. But never released from the master node even the slave is recovered from failure.

After the initialization, I got 3 client connections for each master and 2 client connections for each slave. 

Below is result of the script that I ran to count the client connection with name "Test" on each node.
```
Test has 3 client connection in redis.master1
Test has 3 client connection in redis.master2
Test has 3 client connection in redis.master3
Test has 2 client connection in redis.slave1
Test has 2 client connection in redis.slave2
Test has 2 client connection in redis.slave3
```

Then I stopped one of the slave node "redis.slave1" (I am using docker container, so I ran 'docker stop' which should equivalent to SIGTERM --> grace period --> SIGKILL ). Then I notice the 2 client connections on the stopped slave are migrated to the corresponding master. 

(The master&slave relation of my local setup is like: redis.master1&redis.slave3, redis.master2&redis.slave1, redis.master3&redis.slave2)
```
Test has 3 client connection in redis.master1
Test has 5 client connection in redis.master2
Test has 3 client connection in redis.master3
Could not connect to Redis at redis.slave1: Connection refused
Test has 0 client connection in redis.slave1
Test has 2 client connection in redis.slave2
Test has 2 client connection in redis.slave3
```

Then I restart the "redis.slave1", the 2 client connections are reconnected. But after waiting about 20mins, the 2 extra connections that migrated to its master are never released.
```
Test has 3 client connection in redis.master1
Test has 5 client connection in redis.master2
Test has 3 client connection in redis.master3
Test has 2 client connection in redis.slave1
Test has 2 client connection in redis.slave2
Test has 2 client connection in redis.slave3
```

And here is the redisson log when during the stop and restart of the "redis.slave1"

```
[redisson-netty-2-5] INFO org.redisson.connection.MasterSlaveEntry - master redis.master2/redis.master2:6359 used as slave
[redisson-netty-2-5] WARN org.redisson.cluster.ClusterConnectionManager - slave: redis://redis.slave1:6360 has down for slot ranges: [[5461-10922]]
[redisson-netty-2-28] INFO org.redisson.connection.pool.SlaveConnectionPool - 2 connections initialized for redis.master2/redis.master2:6359
[redisson-netty-2-8] INFO org.redisson.cluster.ClusterConnectionManager - slave: redis://redis.slave1:6360 is up for slot ranges: [[5461-10922]]
[redisson-netty-2-21] INFO org.redisson.connection.pool.SlaveConnectionPool - 2 connections initialized for redis.slave1/redis.slave1:6360
```

When I test the situation when "master node is down", I notice the slave become master and take over the connections. And as soon as the master back alive, and fix the role by failover, the extra connections on the slave node are released. This is the expected behavior.

But the behavior is different when "slave node is down" , why the connections that been taken over by master are not released once the slave node is back alive? And this is causing the redisson client hold the connections more than the defined pool size of configuration.

Thanks for your time and patience.
