### ISSUE TITLE
`getRedisNodes().pingAll()` returning false after Redis sentinel restart in Kubernetes setup

### ISSUE THREAD

**Issue by philmtd** [redisson/redisson#4393]
We have a 3 node sentinel cluster deployed in Kubernetes and use `pingAll()` to check for connection issues.

Now after a restart of Redis `pingAll()` returns `false`. I assume the following, please correct me if I am wrong:

- The Redis connections are based on IP addresses, not hostnames
- Redisson keeps track of the Redis nodes by their IP address

Now in Kubernetes a Redis node will get a new IP address upon restart. Is there a recommended configuration to prevent issues with this? I believe this may impact not only the `pingAll()` method but also other functions?

The redisson configuration is the following:

```yaml
redis:
  redisson:
    config: |-
      sentinelServersConfig:
          password: ${REDIS_AUTHENTICATION_PASSWORD}
          masterName: "mymaster"
          sentinelsDiscovery: false
          sentinelAddresses:
          - "redis://redis-headless.myapp:26379"
```

Note that this issue also occurs, when I explicitly set all 3 nodes in the sentinel addresses list like this:

```yaml
sentinelAddresses:
- "redis://redis-node-0.redis-headless.myapp:26379"
- "redis://redis-node-1.redis-headless.myapp:26379"
- "redis://redis-node-2.redis-headless.myapp:26379"
```
