### ISSUE TITLE
Username is not used

### ISSUE THREAD

**Issue by rhuret** [redisson/redisson#4537]
**Expected behavior**

Use the username of the RedisProperties

**Actual behavior**

Even if the username is set, the `RedissonAutoConfiguration` ignore the username

**Steps to reproduce or test case**

I'm using the following dependency 

```xml
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.17.6</version>
        </dependency>
```

Create a user 'my-username' on the server. Assume the user's password is my-password

```yaml
spring:
  redis:
    host: localhost
    port: 6379
    username: my-username
    password: my-password
```

**Redis version**
7.0.4

**Redisson version**
3.17.6

**Redisson configuration**
No redisson configuration. Just redis
