### ISSUE TITLE
MOVED redirection loop detected. Node rediss://XXXXXXX has further redirect to ...

### ISSUE THREAD

**Issue by leovegas** [redisson/redisson#4656]
Hey. An error occurs while trying to perform operations with the AWS MemoryDB Redis. What could be the problem? 

`org.springframework.dao.InvalidDataAccessApiUsageException: MOVED redirection loop detected. Node rediss://10.51.90.233:6379 has further redirect to rediss://memory-db-0001-001.memory-db.wwwe.memorydb.eu-north-1.amazonaws.com:6379; nested exception is org.redisson.client.RedisException: MOVED redirection loop detected. Node rediss://10.51.90.233:6379 has further redirect to rediss://memory-db-0001-001.memory-db.wwwe.memorydb.eu-north-1.amazonaws.com:6379
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:52) ~[redisson-spring-data-27-3.17.7.jar:3.17.7]
	at org.redisson.spring.data.connection.RedissonExceptionConverter.convert(RedissonExceptionConverter.java:35) ~[redisson-spring-data-27-3.17.7.jar:3.17.7]
	at org.springframework.data.redis.PassThroughExceptionTranslationStrategy.translate(PassThroughExceptionTranslationStrategy.java:44) ~[spring-data-redis-2.7.5.jar:2.7.5]
	at org.redisson.spring.data.connection.RedissonConnection.transform(RedissonConnection.java:204) ~[redisson-spring-data-27-3.17.7.jar:3.17.7]
	at org.redisson.spring.data.connection.RedissonConnection.syncFuture(RedissonConnection.java:199) ~[redisson-spring-data-27-3.17.7.jar:3.17.7]
`

```yaml
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 1
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  password: ""
  subscriptionsPerConnection: 5
  clientName: ""
  username: ""
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - ""
    - ""

  scanInterval: 1000
  ssl: true
  pingConnectionInterval: 0
  keepAlive: false
  tcpNoDelay: false
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.MarshallingCodec> {}
transportMode: "NIO"
```

Spring Boot properties 
```yaml
spring:
  redis:
    host: "clustercfg.memory-db.wwwe.memorydb.eu-north-1.amazonaws.com"
    port: 6379
    timeout: 10s
    connect-timeout: 10s
    username: ""
    password: ""
    ssl: true
```

Spring Boot 2.7.5
```
        <dependency>
            <groupId>org.redisson</groupId>
            <artifactId>redisson-spring-boot-starter</artifactId>
            <version>3.17.7</version>
        </dependency>
```
