### ISSUE TITLE
ElastiCache failover errors in replicatedServersConfig

### ISSUE THREAD

**Issue by niheartent** [redisson/redisson#4893]
My redis deployed as replicated elasticache, 1 master and 1 slave, and I have 2 services in different Redisson version., one is 3.14.1, another is 3.16.7.
When they were in singleServerConfig, they output only a few error logs during  elasticache failover. However , when I change their config to replicatedServersConfig, they output a lot of error logs.
Most of the problems are connection error. When the DNS changed , Redisson cannot access the domain to right IP.
The AWS operations timeline as following:
<html>
<body>

time | events
-- | --
02:53:57~02:56:24 | new master, slave node created 
02:56:41~03:00:26 | add new node  to the cluster as slave node, start full sync the new master node 
03:01:03 | failover, change the new master node to master node
03:03:04 | update DNS, let domains  endpoint point to new  nodes
03:01:18~03:07:01 | The new slave node is synchronized with the new master node
03:08:38 | delete the previous nodes

</body>
</html>
The connections changed as following

**new connections**

![image](https://user-images.githubusercontent.com/57069100/220949012-6b79e36c-a6ec-4c31-8559-f78237146aaf.png)

**current connections**

![image](https://user-images.githubusercontent.com/57069100/220949119-e91dfb6f-2e5f-4784-a4f3-f56ae22f8da1.png)

The error logs time line as following

3.14.1
I cannot see any node add or down in logs
UTC +8
![image](https://user-images.githubusercontent.com/57069100/220951861-7f4839e3-cd0c-48b7-b496-58f77213c356.png)
The error logs timeline as following
<html>
<body>

time | event
-- | --
03:00:47~03:00:55 | ExceptionInterceptor: grpc unexpected exceptionorg.redisson.client.RedisException: READONLY You can't write against a read only slave Send to: **primary_endpoint/new_master_node:6379**
03:01:07~03:01:12 | PingConnectionHandler: Unable to send PING command over channel Send to: **primary_endpoint/new_master_node:6379**
03:04:27~03:07:01 | CacheAspect: Unable to read from redis WriteRedisConnectionException: Unable to write command into connection Send to: **primary_endpoint/previous_master_node:6379** after 1 retry attempts Caused by: io.netty.channel.StacklessClosedChannelException
03:04:27~03:05:42 | CacheAspect: Unable to read from redis org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings.Payload size in bytes: 95. Send to: **reader_endpoint/previous_slave_node:6379** after 1 retry attempts Caused by: io.netty.channel.StacklessClosedChannelException
03:04:29~03:05:38 | ReplicatedConnectionManager: Channel has been closed! Can't write command: (PING) org.redisson.client.WriteRedisConnectionException: Channel has been closed! Can't write command: (PING) Send to: **reader_endpoint/previous_slave_node:6379**
03:04:36 | PingConnectionHandler: Unable to send PING command over channel Send to: **primary_endpoint/previous_master_node:6379**
03:04:36~03:04:46 | PingConnectionHandler: Unable to send PING command over channel Send to: **reader_endpoint/previous_slave_node:6379**
03:05:30~03:05:38 | DefaultPromise: An exception was thrown by org.redisson.misc.RedissonPromisejava.lang.IllegalStateException: Can't find reader endpoint/new slave ip:6379 in slaves! Available slaves:[primary endpoint,reader endpoint]Send to: **reader_endpoint/new_slave_node:6379**
03:10:13 | ExceptionInterceptor: grpc unexpected exception org.redisson.client.RedisTimeoutException: Command still hasn't been written into connection! Increase nettyThreads and/or retryInterval settings. Payload size in bytes: 95. Send to: **primary_endpoint/new_master_node:6379** after 1 retry attempts
03:10:53 | PingConnectionHandler: Unable to send PING command over channel Send to: **primary_endpoint/previous_master_node:6379**
03:10:40~03:13:40 | CacheAspect: Unable to read from redis WriteRedisConnectionException: Unable to write command into connection Send to: **primary_endpoint/previous_master_node:6379** after 1 retry attemptsCaused by: io.netty.channel.StacklessClosedChannelException
03:13:40 | no error logs

</body>
</html>

3.16.7
03:00:55, Other singleServerConfig service output: DNSMonitor: Detected DNS change. Master redis://primary_endpoint:6379 has changed ip from previous_master_node to new_master_node
UTC +8
![image](https://user-images.githubusercontent.com/57069100/220952026-e46287bd-af7d-49ed-a3fd-956ca11c5e7b.png)
<html>
<body>

time | event
-- | --
03:01:00~03:01:02 | get lock monitor:roaming.check.stable.task.lock fail with exception, execute onFail. org.redisson.client.RedisException: Unexpected exception while processing command Caused by: java.lang.IllegalStateException: Only 2 of 1 slaves were synced
03:01:04~03:04:26 | RedisException: READONLY You can't write against a read only slave Send to: **primary_endpoint/previous_master_node:6379**
03:01:06~03:04:26 | get lock monitor:roaming:site.status fail with exception, execute onFail. ERR WAIT cannot be used with slave instances. Please also note that since Redis 4.0 if a slave is configured to be writable (which is not the default) writes to slaves are just local and are not propagated Send to: **primary_endpoint/previous_master_node:6379**
03:04:29~03:04:30 | ReplicatedConnectionManager: slave: [**reader_endpoint/previous_slave_node:6379**] is down
03:04:29~03:04:30 | ReplicatedConnectionManager: org.redisson.client.RedisTimeoutException: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING) Send to: **primary_endpoint**
03:04:29~03:05:35 | ReplicatedConnectionManager: org.redisson.client.RedisTimeoutException: org.redisson.client.RedisTimeoutException: Command execution timeout for command: (PING) Send to: **reader_endpoint**
03:04:30~03:04:31 | MasterPubSubConnectionPool: 1 connections initialized for **primary_endpoint/new_master_node:6379** MasterSlaveEntry: master **primary_endpoint/new_master_node:6379** used as slaveMasterSlaveEntry: master **primary_endpoint/previous_master_node:6379** has changed to **primary_endpoint/new_master_node:6379** MasterConnectionPool: 24 connections initialized for **primary_endpoint/new_master_node:6379**
03:05:32~03:05:36 | PubSubConnectionPool: 1 connections initialized for **reader_endpoint/new_slave_node:6379** ReplicatedConnectionManager: slave: **reader_endpoint/new_slave_node:6379** addedSlaveConnectionPool: 24 connections initialized for **reader_endpoint/new_slave_node:6379**
03:07:45~03:10:01 | get lock monitor:roaming.check.stable.task.lock fail with exception, execute onFail. org.redisson.client.RedisException: Unexpected exception while processing command Caused by: java.lang.IllegalStateException: Only 2 of 1 slaves were synced
03:10:01 | no error logs

</body>
</html>

the config as following
``` yaml
  #3.14.1
replicatedServersConfig:
  connectTimeout: 10000
  masterConnectionPoolSize: 64 
  slaveConnectionPoolSize: 64 
  masterConnectionMinimumIdleSize: 20 
  slaveConnectionMinimumIdleSize: 20 
  readMode: "SLAVE"
  database: 15
  dnsMonitoringInterval: 5000
  idleConnectionTimeout: 10000
  timeout: 3000
  retryAttempts: 1
  retryInterval: 0
  pingConnectionInterval: 10000
  nodeAddresses:
    - primary endpoint
    - reader endpoint
codec: !<org.redisson.codec.FstCodec> {}

#3.16.7
replicatedServersConfig:
  masterConnectionPoolSize: 64
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  slaveConnectionMinimumIdleSize: 24
  readMode: "SLAVE"
  idleConnectionTimeout: 10000
  timeout: 3000
  retryAttempts: 1
  retryInterval: 1500
  pingConnectionInterval: 10000
  database: 0
  dnsMonitoringInterval: 5000
  connectTimeout: 10000
  nodeAddresses:
    - primary endpoint
    - reader endpoint
nettyThreads: 64
codec: !<org.redisson.codec.JsonJacksonCodec> {}
```
Is there something wrong with this?
