### ISSUE TITLE
Redis based Hibernate Cache implementation very slow using RedissonRegionFactory 

### ISSUE THREAD

**Issue by pb00067** [redisson/redisson#5063]
I did some benchmark using Hibernate5.6 and Redis based Hibernate Cache implementation connecting to a local redis instance.
The times to perform a RedissonMapCache#get() or a RedissonRegionFactory#nextTimeStamp() are in average between 700 and 1500 microseconds, which turns  Hibernate being slower than without any 2ndLevelCaching at all.
My workmate did the same thing using .net entity-framework 2ndLevelCache package accessing remote redis instance and he measured access times about 0.4 microseconds in average.
My question is, what makes it so slow?
When I look at the traces then most time the operative threads are stuck here:
```
Unsafe.park(boolean, long) line: not available [native method] [local variables unavailable]	
LockSupport.park(Object) line: 211	
CompletableFuture$Signaller.block() line: 1864	
ForkJoinPool.unmanagedBlock(ForkJoinPool$ManagedBlocker) line: 3463	
ForkJoinPool.managedBlock(ForkJoinPool$ManagedBlocker) line: 3434	
CompletableFuture<T>.waitingGet(boolean) line: 1898	
CompletableFuture<T>.get() line: 2072	
CommandAsyncService.get(RFuture<V>) line: 110	
RedissonMapCache<K,V>(RedissonObject).get(RFuture<V>) line: 89	
RedissonMapCache<K,V>(RedissonMap<K,V>).get(Object) line: 654	
RedissonStorage.getFromCache(Object, SharedSessionContractImplementor) line: 110	
EntityReadWriteAccess(AbstractReadWriteAccess).get(SharedSessionContractImplementor, Object) line: 69	
```
I tried following 3 configurations with all more or less same result:
```
singleServerConfig:
    idleConnectionTimeout: 10000
    connectTimeout: 10000
    timeout: 3000
    retryAttempts: 3
    retryInterval: 1500
    password: null
    subscriptionsPerConnection: 5
    clientName: null
    address: ""redis://localhost:6379""
    subscriptionConnectionMinimumIdleSize: 1
    subscriptionConnectionPoolSize: 50
    connectionMinimumIdleSize: 10
    connectionPoolSize: 64
    database: 0
    dnsMonitoringInterval: 5000
threads: 0
nettyThreads: 0
```

Variant B with following changed/added parameters:
```
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.Kryo5Codec> {}
transportMode: ""NIO"
```

Variant C with following changed/added parameters:
```
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.SnappyCodecV2> {}
transportMode: "NIO"
```

The redis server is a dockerized Redis image (docker pull redis     ,   docker run  -d redis)
