### ISSUE TITLE
Redisson connecting to a cluster fails to recover after temporary outage

### ISSUE THREAD

**Issue by fayf** [redisson/redisson#5096]
My server connects to a Redis cluster deployed in AWS MemoryDB, which has a scheduled maintenance window where AWS occasionally deploys service updates. I encountered the first actual update a few days ago, but Redisson was unable to recover. Here's a log of the messages from Redisson: [redisson.log](https://github.com/redisson/redisson/files/11702165/redisson.log)

**Expected behavior**
After the Redis cluster is back online, Redisson automatically reconnects and recovers

**Actual behavior**
After the Redis cluster is back online, Redisson stays in an error state and fails to recover

**Steps to reproduce or test case**
I'm unsure on how to reproduce

**Redis version**
6.2.x

**Redisson version**
3.19.3

**Redisson configuration**
```
---
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  password: "***"
  username: "***"
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: true
  nameMapper: !<org.redisson.api.DefaultNameMapper> {}
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 180000
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "MASTER"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  dnsMonitoringInterval: 5000
  natMapper: !<org.redisson.api.DefaultNatMapper> {}
  nodeAddresses:
  - "rediss://clustercfg.***.ol7zdz.memorydb.ap-southeast-1.amazonaws.com:6379"
  scanInterval: 5000
  checkSlotsCoverage: true
threads: 16
nettyThreads: 32
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
checkLockSyncedSlaves: true
reliableTopicWatchdogTimeout: 600000
keepPubSubOrder: true
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
cleanUpKeysAmount: 100
nettyHook: !<org.redisson.client.DefaultNettyHook> {}
useThreadClassLoader: true
addressResolverGroupFactory: !<org.redisson.connection.DnsAddressResolverGroupFactory> {}
```
