### ISSUE TITLE
Increased connections and Unable to acquire connection for subscription after upgrading to 3.23.2

### ISSUE THREAD

**Issue by uilton-oliveira** [redisson/redisson#5234]
We tried to update our redisson to 3.23.2 from 3.22.1 and noticied a huge increase in connections and a lot of RedisTimeoutExceptions, after rolling back it to 3.22.1 it's back to normal...

![image](https://github.com/redisson/redisson/assets/7059651/ac5309b4-a9c5-48e2-bb53-d6472a76c559)
![image](https://github.com/redisson/redisson/assets/7059651/6ee793ea-b4f5-4cab-926e-8f63c6161a67)
![image](https://github.com/redisson/redisson/assets/7059651/b0b9a89c-c71c-430a-a2c7-3ae49b73ebec)
![image](https://github.com/redisson/redisson/assets/7059651/05984ed6-4b5f-4ca9-8343-6b29ed053cb3)
![image](https://github.com/redisson/redisson/assets/7059651/9450ee8d-95ff-4d4c-877c-97c56d41a6ca)

```
org.redisson.client.RedisTimeoutException: Unable to acquire connection for subscription after 3 attempts. Increase 'subscriptionsPerConnection' and/or 'subscriptionConnectionPoolSize' parameters.
	at org.redisson.pubsub.PublishSubscribeService.trySubscribe(PublishSubscribeService.java:351)
	at org.redisson.pubsub.PublishSubscribeService.lambda$connect$21(PublishSubscribeService.java:488)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.run(HashedWheelTimer.java:715)
	at io.netty.util.concurrent.ImmediateExecutor.execute(ImmediateExecutor.java:34)
	at io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:703)
	at io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:790)
	at io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:503)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:750)
```

**Expected behavior**
No changes in number of connections and timeouts after upgrade

**Actual behavior**
Connections increased from ~1k to ~3k and too many timeouts

**Steps to reproduce or test case**
We just updated the version

**Redis version**
Redis 7
**Redisson version**
3.23.2
**Redisson configuration**
```
Redisson Config: ---
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 10000
  retryAttempts: 3
  retryInterval: 1500
  credentialsResolver: !<org.redisson.client.DefaultCredentialsResolver> {}
  subscriptionsPerConnection: 10
  clientName: "stg_platform_cluster_staging2"
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  pingConnectionInterval: 30000
  keepAlive: true
  tcpNoDelay: true
  nameMapper: !<com.cortex.system.web.cache.redis.RedisNameMapping> {}
  commandMapper: !<org.redisson.config.DefaultCommandMapper> {}
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 180000
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "MASTER"
  subscriptionConnectionMinimumIdleSize: 2
  subscriptionConnectionPoolSize: 70
  dnsMonitoringInterval: 5000
  natMapper: !<org.redisson.api.DefaultNatMapper> {}
  nodeAddresses:
  - "rediss://clustercfg.redis-comercial-cluster-01.7mjvlu.use1.cache.amazonaws.com:6379"
  scanInterval: 5000
  checkSlotsCoverage: true
  slaveNotUsed: false
threads: 16
nettyThreads: 64
codec: !<org.redisson.codec.CompositeCodec> {}
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
checkLockSyncedSlaves: false
slavesSyncTimeout: 1000
reliableTopicWatchdogTimeout: 600000
keepPubSubOrder: true
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
cleanUpKeysAmount: 100
nettyHook: !<org.redisson.client.DefaultNettyHook> {}
useThreadClassLoader: true
addressResolverGroupFactory: !<org.redisson.connection.RoundRobinDnsAddressResolverGroupFactory> {}
```
