### ISSUE TITLE
NPE Bug: org.redisson.spring.starter.RedissonAutoConfiguration

### ISSUE THREAD

**Issue by hpsocket** [redisson/redisson#5314]
**Expected behavior**
startup successfully
**Actual behavior**
NPE in org.redisson.spring.starter.RedissonAutoConfiguration
line: 285

```
           
    if (hasConnectionDetails()) {
        ObjectProvider<RedisConnectionDetails> provider = ctx.getBeanProvider(RedisConnectionDetails.class);
        // b == null !
        RedisConnectionDetails b = provider.getIfAvailable();
        if (b.getStandalone() != null) {
            database = b.getStandalone().getDatabase();
            singleAddr = prefix + b.getStandalone().getHost() + ":" + b.getStandalone().getPort();
        }
    }
```

**Steps to reproduce or test case**
startup spring-boot project
**Redis version**
7.0
**Redisson version**
3.23.4
**Redisson configuration**
```
spring.data.redis:
  host: 192.168.56.23
  port: 6379
  #username: 
  #password: 
  clientName: ${spring.application.name}
```
