### ISSUE TITLE
Not able to connect redis sentinel using redisson in spring boot in local?

### ISSUE THREAD

**Issue by kumarsen26** [redisson/redisson#5335]
1. Running redis-sentinel server using docker compose in local by following [bitnami/redis-sentinel/](https://hub.docker.com/r/bitnami/redis-sentinel/) and [Spring Boot 3,Redis Sentinel](https://medium.com/@htyesilyurt/spring-boot-3-redis-sentinel-lettuce-client-and-docker-compose-for-high-availability-1f1e3c372a5a).
2. updated REDIS_MASTER_HOST=127.0.0.1 to sentinel server in docker compose file
3.` docker compose up -d`
4. Running my Spring boot application locally with the below properies
```
spring:
  data:
    redis:
      password: redispassword
      sentinel:
        master: mymaster
        nodes:
          - 127.0.0.1:26379
          - 127.0.0.1:26380
          - 127.0.0.1:26381
```
Application is not starting and getting below error

> Failed to instantiate [org.redisson.api.RedissonClient]: Factory method 'redisson' threw exception with message: SENTINEL SENTINELS command returns less than 2 nodes or connection can't be established to some of them! At least two sentinels should be defined in Redis configuration.

When I containerize and add my application to the same docker compose file as another service, it works with below properties.

> SPRING_DATA_REDIS_SENTINEL_MASTER: redismaster
> SPRING_DATA_REDIS_SENTINEL_NODES: redis-sentinel:26382,redis-sentinel2:26380,redis-sentinel3:26381

is redisson does not support to access the sentinel configuration outside docker locally?
