### ISSUE TITLE
Invalid XTRIM command when truncating a stream

### ISSUE THREAD

**Issue by munk** [redisson/redisson#5353]
**Expected behavior**
The stream should have a length of 0

**Actual behavior**
The trim call fails with this error:

```
org.redisson.client.RedisException: ERR wrong number of arguments for 'xtrim' command. channel: [id: 0x22b6ab4b, L:/127.0.0.1:58615 - R:127.0.0.1/127.0.0.1:6379] command: (XTRIM), promise: java.util.concurrent.CompletableFuture@66699ade[Not completed, 1 dependents], params: [myStream]
```

**Steps to reproduce or test case**

Using redis-cli, this is what should happen
```
➜  ~ redis-cli
127.0.0.1:6379> XLEN mystream
(integer) 0
127.0.0.1:6379> XADD mystream * k v
"1696633158481-0"
127.0.0.1:6379> XLEN mystream
(integer) 1
127.0.0.1:6379> XTRIM mystream MAXLEN = 0
(integer) 1
127.0.0.1:6379> XLEN mystream
(integer) 0
```

The following java code should produce the same behavior, but it does not. Instead, it results in the error shown above.

```

import org.redisson.Redisson;
import org.redisson.api.RStream;
import org.redisson.api.RedissonClient;
import org.redisson.api.stream.StreamTrimArgs;

public class Trim {
    public static void main(String[] args) {
        RedissonClient redisson = Redisson.create();
        RStream<String, String> stream = redisson.getStream("myStream");
        StreamTrimArgs trimArgs = StreamTrimArgs.maxLen(0).noLimit();
        long trimmed = stream.trim(trimArgs);
        System.out.println(trimmed);
    }
}
```

Redisson is instead producing this:

```
127.0.0.1:6379> XTRIM mystream
(error) ERR wrong number of arguments for 'xtrim' command
```

**Redis version**
7.2.0

**Redisson version**
3.23.4

**Redisson configuration**

```
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  credentialsResolver: !<org.redisson.client.DefaultCredentialsResolver> {}
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: true
  nameMapper: !<org.redisson.api.DefaultNameMapper> {}
  commandMapper: !<org.redisson.config.DefaultCommandMapper> {}
  address: "redis://localhost:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 64
  database: 0
  dnsMonitoringInterval: 5000
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.JsonJacksonCodec> {}
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
checkLockSyncedSlaves: true
slavesSyncTimeout: 1000
reliableTopicWatchdogTimeout: 600000
keepPubSubOrder: true
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
cleanUpKeysAmount: 100
nettyHook: !<org.redisson.client.DefaultNettyHook> {}
useThreadClassLoader: true
addressResolverGroupFactory: !<org.redisson.connection.SequentialDnsAddressResolverFactory> {}
lazyInitialization: true
```
