### ISSUE TITLE
Expiring entries under load results in Hibernate retrieving a null value

### ISSUE THREAD

**Issue by contentfree** [redisson/redisson#5404]
**Expected behavior**
Redisson / Hibernate should return the correct value

**Actual behavior**
Redis (or some other mechanism) results in null value

**Steps to reproduce or test case**
I have a cached entity "Campaign". It's cache region has a TTL of one minute. A related entity runs getCampaign() and sometimes returns null for a period of time (one minute-ish; see screenshot). 

Under consistent load this morning we experienced application errors in spikes due to this. Here's a screenshot of our error frequencies:

<img width="1285" alt="image" src="https://github.com/redisson/redisson/assets/10958/b4a7ea45-c236-4ee9-847e-d7e5121739fd">

**Redis version**
6.2.6

**Redisson version**
3.23.5 (w/ redisson-hibernate-6)

**Redisson configuration**
```
singleServerConfig:
  idleConnectionTimeout: ${idleConnectionTimeout:-15000}
  connectTimeout: ${connectTimeout:-10000}
  timeout: ${timeout:-5000}
  retryAttempts: ${retryAttempts:-5}
  retryInterval: ${retryInterval:-1000}
  password: ${password:-null}
  subscriptionsPerConnection: ${subscriptionsPerConnection:-5}
  clientName: ${clientName:-null}
  address: ${REDIS_URL:-redis://localhost:6379}
  subscriptionConnectionMinimumIdleSize: ${subscriptionConnectionMinimumIdleSize:-1}
  subscriptionConnectionPoolSize: ${subscriptionConnectionPoolSize:-50}
  connectionMinimumIdleSize: ${connectionMinimumIdleSize:-2}
  connectionPoolSize: ${hibernate.hikari.maximumPoolSize:-500}
  database: ${database:-0}
  dnsMonitoringInterval: ${dnsMonitoringInterval:-5000}
threads: ${threads:-0}
codec: ${codec:-!<org.redisson.codec.SnappyCodecV2> {}}
eventLoopGroup: ${eventLoopGroup:-null}
```

What else could I provide to assist debugging? I'm not sure it's related to expiration, but the fact that it comes and goes is suspicious!
