### ISSUE TITLE
Attempt to unlock lock, not locked by current thread by node id

### ISSUE THREAD

**Issue by huomozhihen** [redisson/redisson#5473]
This exception occured in my application. And i saw the same question in #4871 
Then I upgraded redisson to the lastest version in which the problem should be fixed.
UnExceptedly, the problem still exsits in redisson-3.24.3. I hope to know why it occurs and how to fix it. Thanks.

**Redisson version**
3.24.3

**Comment by mrniko** [comment]
Is there any code example to reproduce it?

**Comment by uilton-oliveira** [comment]
We tried to upgrade our redisson from 3.22.1 to 3.25.2 and noticied a huge increase in this error (Attempt to unlock lock, not locked by current thread by node id)
![image](https://github.com/redisson/redisson/assets/7059651/2aec9deb-4808-42fd-9157-627fc35b3677)


Also, we noticied a increase in cases where the cache appear to not be propely synced among all nodes when using RLocalCachedMap...

We had been forced to downgrade it to 3.22.1 once again (for third time)
Previous attempts:
- Oct. 3 = 3.22.1 -> 3.23.2
- Nov. 28 = 3.22.1 -> 3.24.3
- Dev. 19 = 3.22.1 -> 3.25.2

All our attempts was frustrated due to some bug, some that was fixed later, so we tried to upgrade, but then there's some new bug that force us to downgrade again :(

3.22.1 is the most "stable" that we found so far, but there's still a annoying bug that we think that it was already fixed in recent versions that cause the redisson not being able to connect to redis some times at startup, forcing us to kill the EC2 instance and starting a new, so it start working again..


Our config:
```
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 10000
  subscriptionTimeout: 7500
  retryAttempts: 3
  retryInterval: 1500
  credentialsResolver: !<org.redisson.client.DefaultCredentialsResolver> {}
  subscriptionsPerConnection: 10
  clientName: "prd_platform_cluster_4"
  sslEnableEndpointIdentification: true
  sslProvider: "JDK"
  pingConnectionInterval: 30000
  keepAlive: true
  tcpKeepAliveCount: 0
  tcpKeepAliveIdle: 0
  tcpKeepAliveInterval: 0
  tcpUserTimeout: 0
  tcpNoDelay: true
  nameMapper: !<com.cortex.system.web.cache.redis.RedisNameMapping> {}
  commandMapper: !<org.redisson.config.DefaultCommandMapper> {}
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 180000
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "SLAVE"
  subscriptionMode: "MASTER"
  subscriptionConnectionMinimumIdleSize: 2
  subscriptionConnectionPoolSize: 70
  dnsMonitoringInterval: 5000
  failedSlaveNodeDetector: !<org.redisson.client.FailedConnectionDetector> {}
  natMapper: !<org.redisson.api.DefaultNatMapper> {}
  nodeAddresses:
  - "rediss://xxxx.use1.cache.amazonaws.com:6379"
  scanInterval: 5000
  checkSlotsCoverage: true
threads: 16
nettyThreads: 64
codec: !<org.redisson.codec.CompositeCodec> {}
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 30000
checkLockSyncedSlaves: false
slavesSyncTimeout: 1000
reliableTopicWatchdogTimeout: 600000
keepPubSubOrder: true
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
cleanUpKeysAmount: 100
nettyHook: !<org.redisson.client.DefaultNettyHook> {}
useThreadClassLoader: true
addressResolverGroupFactory: !<org.redisson.connection.RoundRobinDnsAddressResolverGroupFactory> {}
lazyInitialization: false
protocol: "RESP2"
```
