### ISSUE TITLE
The value obtained by get in the Redis cluster is null

### ISSUE THREAD

**Issue by GuanTu** [redisson/redisson#5496]
English is not my native language, so I will translate

**Expected behavior**

`redisTemplate.opsForValue().get(redis_key)` result is not null

**Actual behavior**

`redisTemplate.opsForValue().get(redis_key)` result is null, and the results of the SpringBootDataRedis default configuration (lettuce) should not be empty

**Steps to reproduce or test case**

Attach a repetition engineering, perform unit test `RedissonSpring2ApplicationTests.xxx()`

[redisson-spring2.zip](https://github.com/redisson/redisson/files/13618423/redisson-spring2.zip)

**Redis version**
```
redis_version:7.2.1
# Cluster
cluster_enabled:1
```
**Redisson version**
```
Spring Boot 2.7.8
Redisson 3.25.0
```
**Redisson configuration**
default

**Comment by michael19960921** [comment]
原来这是一个BUG啊...我也遇到了...我还一直以为是程序的BUG

**Comment by michael19960921** [comment]
Originally, this is a bug. I have also encountered it. I have been thinking that it is a bug in my program. In a cluster environment, redis clearly has data, but redisson is unable to read the content.

**Comment by michael19960921** [comment]
I encountered this bug as well, and I thought it was a bug in my program. In a clustered environment, Redis clearly had data, but Redisson couldn't read it. I am also using version 3.25.0 of Redisson and version 3.2.0 of Spring Boot.

**Comment by mrniko** [comment]
Thanks for the test project. Unable to reproduce. I attached the output log.
[out.log](https://github.com/redisson/redisson/files/13634959/out.log)

Did you try to remover username and/or password in application.yaml ?

**Comment by GuanTu** [comment]
> Thanks for the test project. Unable to reproduce. I attached the output log. [out.log](https://github.com/redisson/redisson/files/13634959/out.log)
> 
> Did you try to remover username and/or password in application.yaml ?

@mrniko Yes, you are right, removing the Redis user name can successfully get the value. However, due to security requirements, Redis cluster must set the user name and password, could you please help troubleshoot the problem?

**Comment by mrniko** [comment]
Can you share Redis config as well?

**Comment by mrniko** [comment]
Unable to reproduce.

Can you apply setting below to spring configuration and share the output?
```yaml
logging:
  level:
    org.redisson: "TRACE"
```

**Comment by GuanTu** [comment]
@mrniko Strangely enough, when I removed the acl configuration, restarted redis and set the acl again, test passed. However, the test failed to clear the data directory to rebuild the cluster.
I uploaded related configurations and logs.
[fail test.log](https://github.com/redisson/redisson/files/13680550/test.log)
[docker-compose-redis-cluster.zip](https://github.com/redisson/redisson/files/13680580/docker-compose-redis-cluster.zip)

**Comment by GuanTu** [comment]
application.yaml
```yaml
spring:
  application:
    name: Server-Redis-Starter
  redis:
    cluster:
      nodes: 192.168.16.98:7001,192.168.16.98:7002,192.168.16.98:7003,192.168.16.98:7004,192.168.16.98:7005,192.168.16.98:7006
      max-redirects: 5
    username: myuser
    password: 123456
    timeout: 6000ms


logging:
  level:
    org.redisson: "TRACE"

```
