### ISSUE TITLE
Urgent! Timeout issue with writing messages to RScoredSortedSet.

### ISSUE THREAD

**Issue by uzdz** [redisson/redisson#5786]
**Expected behavior**
Calling the `produce` method allows Redisson to successfully store data in Redis.

```java
import lombok.extern.slf4j.Slf4j;
import org.redisson.api.RScoredSortedSet;
import org.redisson.api.RedissonClient;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

/**
 * Redis 实现有序队列, 基于 sorted set 实现
 *
 * @author zhaoshuguang
 */
@Slf4j
public class RedisMessageQueue {

    private final RScoredSortedSet<String> queue;

    public RedisMessageQueue(RedissonClient redisson, String queueName) {
        this.queue = redisson.getScoredSortedSet(queueName);
    }

    public int produce(Collection<String> values) {
        // 生产消息，将消息添加到有序集合中
        long score = System.currentTimeMillis();
        Map<String, Double> elements = new HashMap<>();
        for (String value : values) {
            elements.put(value, (double) score);
        }
        long time = System.currentTimeMillis();
        int success = queue.addAll(elements);
        log.info("RedisMessageQueue.product, time={}ms, message={}, success={}",
                System.currentTimeMillis() - time, values, success);
        return success;
    }

    public boolean produce(String message) {
        // 生产消息，将消息添加到有序集合中
        long time = System.currentTimeMillis();
        boolean success = queue.add(System.currentTimeMillis(), message);
        log.info("RedisMessageQueue.product, time={}ms, message={}, success={}",
                System.currentTimeMillis() - time, message, success);
        return success;
    }

    public String consume() {
        // 消费消息，从有序集合中获取分数最低的消息
        return queue.pollFirst();
    }

    public boolean remove(String message) {
        // 删除指定消息
        return queue.remove(message);
    }

    public void startConsuming(Processor processor) {
        // 添加消息监听器，监听新消息的添加事件
        queue.subscribeOnFirstElements(processor::process);
    }
}
```

**Actual behavior**
When the version is `3.16.0`, an error occurs randomly when invoking `queue.addAll`. While most messages are successfully stored in Redis, a few encounter errors, resulting in the following content:

`Command still hasn't been written into connection! Try to increase nettyThreads setting. Payload size in bytes: 6. Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@1545971463 [redisClient=[addr=redis://r-2zeef2ue2pun4wkqqu.redis.rds.aliyuncs.com:6379], channel=[id: 0xbaf9f5c7, L:/172.16.6.200:54908 - R:r-2zeef2ue2pun4wkqqu.redis.rds.aliyuncs.com/172.17.212.0:6379], currentCommand=CommandData [promise=RedissonPromise [promise=ImmediateEventExecutor$ImmediatePromise@2ab901ae(success: 967206)], command=(BZPOPMIN), params=[user:task:compute:queue, 0], codec=org.redisson.client.codec.StringCodec]], command: (ZADD), params: [user:task:compute:queue, 1713199536148, PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)] after 1 retry attempts`

Even after upgrading to version `3.28.0`, the error still persists, displaying the following content:

`Command still hasn't been written into connection! Check CPU usage of the JVM. Check connection with Redis node: r-2zeef2ue2pun4wkqqu.redis.rds.aliyuncs.com/172.17.212.0:6379 for TCP packet drops. Try to increase nettyThreads setting.  Node source: NodeSource [slot=0, addr=null, redisClient=null, redirect=null, entry=null], connection: RedisConnection@520830206 [redisClient=[addr=redis://r-2zeef2ue2pun4wkqqu.redis.rds.aliyuncs.com:6379], channel=[id: 0x75bfe2f6, L:/172.16.4.247:49886 - R:r-2zeef2ue2pun4wkqqu.redis.rds.aliyuncs.com/172.17.212.0:6379], currentCommand=CommandData [promise=java.util.concurrent.CompletableFuture@27c35253[Completed normally], command=(BZPOPMIN), params=[user:task:compute:queue, 0], codec=org.redisson.client.codec.StringCodec], usage=1], command: (ZADD), params: [user:task:compute:queue, 1713199342471, PooledUnsafeDirectByteBuf(ridx: 0, widx: 6, cap: 256)] after 3 retry attempts`

**Steps to reproduce or test case**

Since the stored data is uniform and there are no large messages, I can't replicate the issue in the development environment. However, it sporadically occurs in the production environment, causing significant frustration.

However, it's certain that invoking `queue.addAll` to store data in the production environment occurs more frequently than in the development environment. Despite this, I'm still unable to replicate the issue in the development environment.

**Redis version**

Aliyun Redis 5.0.13

**Redisson version**
```xml
<dependency>
	<groupId>org.redisson</groupId>
	<artifactId>redisson-spring-boot-starter</artifactId>
	<version>3.16.0</version>
</dependency>
```

Even after upgrading to 3.28.0, the error still persists.
```xml
<dependency>
	<groupId>org.redisson</groupId>
	<artifactId>redisson-spring-boot-starter</artifactId>
	<version>3.28.0</version>
	<exclusions>
		<exclusion>
			<groupId>org.redisson</groupId>
			<artifactId>redisson-spring-data-32</artifactId>
		</exclusion>
	</exclusions>
</dependency>

<dependency>
	<groupId>org.redisson</groupId>
	<artifactId>redisson-spring-data-24</artifactId>
	<version>3.28.0</version>
</dependency>
```

**Redisson configuration**
```yaml
spring:
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 5000
          retryAttempts: 1
          retryInterval: 3000
          password: new_task_package:EI9iGAnyNf
          subscriptionsPerConnection: 5
          clientName: null
          address: ""
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          connectionPoolSize: 64
          database: 9
          dnsMonitoringInterval: 5000
        threads: 64
        nettyThreads: 256
        codec: !<org.redisson.client.codec.StringCodec> {}
        transportMode: "NIO"
```
**Tips**
I want to emphasize that I've increased nettyThreads and retryInterval, but the problem still persists. This renders our company unable to use the current framework as a Redis client!
