### ISSUE TITLE
redisson:tomcat_notified_nodes keys created without an expiration

### ISSUE THREAD

**Issue by ehardy** [redisson/redisson#6022]
### Redis version

Redis Cloud, but can be reproduced using latest Redis running in Docker.

### Redisson version

latest 3.32.0

### Redisson configuration

In Tomcat's web.xml:
```xml
<Manager className="org.redisson.tomcat.RedissonSessionManager"
			 configPath="${catalina.base}/conf/redisson.yaml"
			 readMode="MEMORY"
			 updateMode="AFTER_REQUEST"
			 broadcastSessionEvents="true" />
```

redisson.yaml:
```yaml
singleServerConfig:
  address: "redis://localhost:${REDIS_PORT:-6379}"
  connectTimeout: 30000
  timeout: 30000
codec: !<org.redisson.codec.SerializationCodec> {}
```

### What is the Expected behavior?

All `redisson:tomcat_notified_nodes` keys get created with a 60s expiration.

### What is the Actual behavior?

Depending on timing, there are `redisson:tomcat_notified_nodes` keys created without the 60s expiration, which leads to an accumulation of such keys, and at worse, valid session keys getting evicted by Redis.

### Additional information

A fix for this situation can be found in #6021
