### ISSUE TITLE
How to configure failedSlaveNodeDetector with org.redisson.client.FailedCommandsTimeoutDetector in yaml?

### ISSUE THREAD

**Issue by spice-wolf** [redisson/redisson#6082]
> maven dependency: redisson-spring-boot-starter:3.29.0

Hello, i try to configure `failedSlaveNodeDetector` in yaml file and i intend to use `org.redisson.client.FailedCommandsTimeoutDetector` as the specific instance. Just like this:
```yaml
spring:
  redis:
    redisson: 
      config: |
        clusterServersConfig:
          failedSlaveNodeDetector: !<org.redisson.client.FailedCommandsTimeoutDetector> {}
```

But some error occurred:
```java
Suppressed: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of org.redisson.client.FailedCommandsTimeoutDetector (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
 at [Source: (StringReader); line: 33, column: 82] (through reference chain: org.redisson.config.Config["clusterServersConfig"]->org.redisson.config.ClusterServersConfig["failedSlaveNodeDetector"])
```
Could you please give me a demo how to configure it correctly?

**Comment by mrniko** [comment]
Thanks for pointing out. It has been fixed.

Below is the usage example:

```yaml
spring:
  redis:
    redisson: 
      config: |
        clusterServersConfig:
              failedSlaveNodeDetector: !<org.redisson.client.FailedCommandsTimeoutDetector>
                          checkInterval: 2000
                          failedCommandsLimit: 20
```
