### ISSUE TITLE
Question about SpringBootTest

### ISSUE THREAD

**Issue by kimhyun5u** [redisson/redisson#6122]
Hi! I'm using org.redisson:redisson-spring-boot-starter:3.35.0

When I test @SpringBootTest in not depended part, I just throw `Error creating bean with name 'redissonClient'`.

If redis is unable to connect. it just invoke that exception.

How could I skip this creating bean of reddison configuration at bootload timing?

**Comment by haedoang** [comment]
i added it in my test properites 

```yml
spring:
  autoconfigure:
    exclude:
      - org.redisson.spring.starter.RedissonAutoConfigurationV2
```      

[https://github.com/redisson/redisson/tree/master/redisson-spring-boot-starter#q-how-to-disable-redisson](url)
