### ISSUE TITLE
Thread blocked while execute lua script got exception with `org.redisson.command.CommandAsyncExecutor#syncedEvalWithRetry` and get result from the future

### ISSUE THREAD

**Issue by TigerZCoder** [redisson/redisson#6187]
### Redis version

6.2.9

### Redisson version

3.27.1

### Redisson configuration

from `redisson.getConfig().toYAML()`
```yaml
---
singleServerConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 5000
  subscriptionTimeout: 7500
  retryAttempts: 3
  retryInterval: 10000
  password: "123456"
  credentialsResolver: !<org.redisson.client.DefaultCredentialsResolver> {}
  subscriptionsPerConnection: 5
  sslEnableEndpointIdentification: false
  sslProvider: "JDK"
  pingConnectionInterval: 0
  keepAlive: false
  tcpKeepAliveCount: 0
  tcpKeepAliveIdle: 0
  tcpKeepAliveInterval: 0
  tcpUserTimeout: 0
  tcpNoDelay: true
  nameMapper: !<org.redisson.api.DefaultNameMapper> {}
  commandMapper: !<org.redisson.config.DefaultCommandMapper> {}
  address: "redis://127.0.0.1:6379"
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 512
  database: 0
  dnsMonitoringInterval: 5000
threads: 32
nettyThreads: 64
codec: !<org.redisson.client.codec.StringCodec> {}
referenceEnabled: true
transportMode: "NIO"
lockWatchdogTimeout: 300000
checkLockSyncedSlaves: true
slavesSyncTimeout: 1000
reliableTopicWatchdogTimeout: 600000
keepPubSubOrder: true
useScriptCache: false
minCleanUpDelay: 5
maxCleanUpDelay: 1800
cleanUpKeysAmount: 100
nettyHook: !<org.redisson.client.DefaultNettyHook> {}
useThreadClassLoader: true
addressResolverGroupFactory: !<com.hundsun.jrescloud.lock.redis.redisson.DistributedLockAddressResolverFactory> {}
lazyInitialization: false
protocol: "RESP2"

```

### What is the Expected behavior?

when encounted Exception while execute `org.redisson.connection.ServiceManager#execute(java.util.concurrent.atomic.AtomicInteger, java.util.concurrent.CompletableFuture<T>, java.util.function.Supplier<java.util.concurrent.CompletionStage<T>>)`, 
pass the underlying RedisException normally

### What is the Actual behavior?

[in the source of ServiceManager of version 3.27.1 at line 504](https://github.com/redisson/redisson/blob/d845e4ba5977dc7eb9bd50397bb68fef2f1a8458/redisson/src/main/java/org/redisson/connection/ServiceManager.java#L504)
`e.getCause().getMessage()` will cause an exception when `e.getCause()` returns `null` , which will cause `result.completeExceptionally(e)` on line 516 to not be executed, thus blocking the external thread waiting for the `Future` to complete.

### Additional information

You can easily reproduce the problem as follows:

1. just prepare a buggy lua script like `redis.call('go', 'aaa')`
2. execute the script via `org.redisson.command.CommandAsyncExecutor#syncedEvalWithRetry`
3. call `org.redisson.RedissonObject#get` with the `future` returned by step 2

you are blocking here ...
