### ISSUE TITLE
Hibernate region_prefix configuration doesn't apply to redis key redisson-hibernate-timestamp

### ISSUE THREAD

**Issue by rockinrimmer** [redisson/redisson#6283]
### Redis version

Any

### Redisson version

3.38.1

### Redisson configuration

I don't believe the Redisson config makes a difference but this is the Spring Boot/Hibernate config to set a Hibernate L2 cache region prefix.

```yaml
spring:
  jpa:
    properties:
      hibernate:
        cache:
          region_prefix: test-prefix
```

### What is the Expected behavior?

When the `region_prefix` Hibernate cache configuration is set then all redis keys should be prefixed with that prefix, including the key `redisson-hibernate-timestamp`.

### What is the Actual behavior?

The `redisson-hibernate-timestamp` is not prefixed.

Other keys are prefixed correctly.
