### ISSUE TITLE
Eventhough the read_mode was Master_slave, the read queries are not going on the master node.

### ISSUE THREAD

**Issue by ShashankSByakod37** [redisson/redisson#6291]
We have below redisson config, where `readMode` was made as `MASTER_SLAVE`, still the read queries are not going to the master node of the cluster but it's behaving as `SLAVE` on reads. 

Below is the method being used from Redisson client library.

```
private RedissonClient redissonClient;
status = redissonClient.getBitSet(bitKeyName).get(bitIndex);
```

**Below is the client config:**
```
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 500
  failedSlaveReconnectionInterval: 3000
  failedSlaveNodeDetector: !<org.redisson.client.FailedConnectionDetector> {}
  password: null
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "MASTER_SLAVE"
  subscriptionMode: "SLAVE"
  nodeAddresses:
    - "redis://<host-url>:6379"
  scanInterval: 1000
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: true
threads: 16
nettyThreads: 32
codec:
  class: org.redisson.client.codec.StringCodec
transportMode: "NIO"
```

Can you pls help here asap? this is happening on the production.
