### ISSUE TITLE
scheduleClusterChangeCheck call addSlave method when isSlaveNotUsed is true

### ISSUE THREAD

**Issue by polarisGitHub** [redisson/redisson#6339]
isubscriptionMode and readMode set to master,so isSlaveNotUsed is true

```java
// init collection
@Override
public void doConnect(Function<RedisURI, String> hostnameMapper) {
      for (ClusterPartition partition : partitions) {
          if (partition.isMasterFail()) {
              failedMasters.add(partition.getMasterAddress().toString());
              continue;
          }
          if (partition.getMasterAddress() == null) {
              throw new IllegalStateException("Master node: " + partition.getNodeId() + " doesn't have an address.");
          }
          // 1.add slave init master
          CompletionStage<Void> masterFuture = addMasterEntry(partition, cfg);
          masterFutures.add(masterFuture.toCompletableFuture());
      }

    // 2.add slave schedule check
    scheduleClusterChangeCheck(cfg);
}
```

1.  In addMasterEntry, addSlaveEntry will not be finally called 

```java
private CompletionStage<Void> addMasterEntry(ClusterPartition partition, ClusterServersConfig cfg) {
            // use single or master slave entry
            if (config.isSlaveNotUsed()) {
                entry = new SingleEntry(this, config);
            } else {
                Set<String> slaveAddresses = partition.getSlaveAddresses().stream()
                                                                            .filter(r -> !partition.getFailedSlaveAddresses().contains(r))
                                                                            .map(r -> r.toString())
                                                                            .collect(Collectors.toSet());
                config.setSlaveAddresses(slaveAddresses);

                entry = new MasterSlaveEntry(ClusterConnectionManager.this, config);
            }

            CompletableFuture<RedisClient> f = entry.setupMasterEntry(new RedisURI(config.getMasterAddress()), configEndpointHostName);
            return f.thenCompose(masterClient -> {
                // not not call addSlaveEntry in initSlaveBalancer when use master
                if (!config.isSlaveNotUsed()) {
                    CompletableFuture<Void> fs = entry.initSlaveBalancer(r -> configEndpointHostName);
                }
            });
        });
    }
```

2.  In scheduleClusterChangeCheck, addSlaveEntry will be called. `checkSlaveNodesChange -> addRemoveSlaves -> addRemoveSlaves -> addSlaveEntry`

```java
private CompletableFuture<Set<RedisURI>> addRemoveSlaves(MasterSlaveEntry entry, ClusterPartition currentPart, ClusterPartition newPart) {
      for (RedisURI uri : addedSlaves) {
          //add addSlave without judging isSlaveNotUsed
          CompletableFuture<Void> slaveUpFuture = entry.addSlave(uri, configEndpointHostName);
          CompletableFuture<Void> f = slaveUpFuture.thenAccept(res -> {
              currentPart.addSlaveAddress(uri);
              log.info("slave: {} added for master {} and slot ranges: {}",
                      currentPart.getMasterAddress(), uri, currentPart.getSlotRanges());
              entry.excludeMasterFromSlaves(uri);
          });
          futures.add(f);
      }

      CompletableFuture<Void> f = CompletableFuture.allOf(futures.toArray(new CompletableFuture[0]));
      return f.thenApply(r -> addedSlaves);
  }
```

When adding a new slave node, slave node data that will not be used is added because isSlaveNotUsed is true. 
Whether it is necessary to add isSlaveNotUsed judgment in addRemoveSlaves, or not execute checkSlaveNodesChange when isSlaveNotUsed is true?

**Comment by polarisGitHub** [comment]
```yml
clusterServersConfig:
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 3
  retryInterval: 1500
  failedSlaveReconnectionInterval: 3000
  failedSlaveCheckInterval: 60000
  subscriptionsPerConnection: 5
  clientName: null
  loadBalancer: !<org.redisson.connection.balancer.RoundRobinLoadBalancer> {}
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  slaveConnectionMinimumIdleSize: 24
  slaveConnectionPoolSize: 64
  masterConnectionMinimumIdleSize: 24
  masterConnectionPoolSize: 64
  readMode: "MASTER"
  subscriptionMode: "MASTER"
  nodeAddresses:
    - "redis://xxxxxxxx:6379"
  scanInterval: 1000
  pingConnectionInterval: 30000
  keepAlive: false
  tcpNoDelay: false
threads: 16
nettyThreads: 32
codec: !<org.redisson.codec.JsonJacksonCodec> {}
transportMode: "NIO"
```

I created a new redis cluster with 3 masters and 3 slaves. There are only system monitoring links on redis.
![1](https://github.com/user-attachments/assets/1a977ed2-ebdd-4714-ac40-f5b756651bab)
```java
public class RedissonUtils {

    public static void main(String[] args) throws IOException, InterruptedException {
        PathMatchingResourcePatternResolver resolver = new PathMatchingResourcePatternResolver();
        Resource resource = resolver.getResource("classpath:redisson.yml");
        Redisson redissonClient = (Redisson)Redisson.create(Config.fromYAML(resource.getInputStream()));
    }
}
```
Then I created a client and you can see that no connection was established from the RedissonClient at the beginning.
![2](https://github.com/user-attachments/assets/89295109-61f1-4c05-9685-3ec947dd94e3)

But when I add a new slave node, the connection is established to this slave node. `It is expected that in the case of reading the master, the new slave node does not need to establish a connection.`
![3](https://github.com/user-attachments/assets/10fe58e1-b7af-471f-9f23-e490b150f7a9)
